#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/path
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS= allpaths.c clausesel.c costsize.c hashutils.c indxpath.c \
	joinpath.c joinrels.c joinutils.c mergeutils.c orindxpath.c \
	prune.c

# not ready yet: predmig.c xfunc.c



