# $PostgreSQL$

subdir = contrib/string
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = string_io
DATA_built = string_io.sql
DOCS = README.string_io

include $(top_srcdir)/contrib/contrib-global.mk
