#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/cache
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= catcache.c inval.c rel.c relcache.c syscache.c lsyscache.c fcache.c

