#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/time
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= tqual.c
