#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/ipc
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= ipc.c ipci.c s_lock.c shmem.c shmqueue.c sinval.c \
	sinvaladt.c spin.c
