#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

.DEFAULT:
	$(MAKE) -C regress $@
