#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

.DEFAULT all:
	$(MAKE) -C bench $@
	$(MAKE) -C regress $@
