#-------------------------------------------------------------------------
#
# $PostgreSQL$
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/euc_jis_2004_and_shift_jis_2004
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		= euc_jis_2004_and_shift_jis_2004

include $(srcdir)/../proc.mk
