# $Header$

subdir = contrib/array
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = array_iterator
DATA_built = array_iterator.sql
DOCS = README.array_iterator

include $(top_srcdir)/contrib/contrib-global.mk
