#
# Makefile for the access methods module
#
# $PostgreSQL$
#

subdir = src/backend/access
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = common gist hash heap index nbtree transam gin

include $(top_srcdir)/src/backend/common.mk
