#-------------------------------------------------------------------------
#
# Makefile
#    Makefile for src/pl/plpgsql (PostgreSQL's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SRCDIR= ../..
include $(SRCDIR)/Makefile.global


.DEFAULT all install clean dep depend distclean:
	-$(MAKE) -C src $@

