#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/smgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= md.c mm.c smgr.c smgrtype.c
