#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/prep
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= archive.c prepqual.c preptlist.c prepunion.c
