#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/common
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= heaptuple.c heapvalid.c indextuple.c indexvalid.c printtup.c \
	scankey.c tupdesc.c

