#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for tools/mkldexport
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SHPROG=mkldexport

MKDIR=	../../mk
include ../../Makefile.global
include $(MKDIR)/postgres.mk

include $(MKDIR)/postgres.shell.mk
