#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for tools/mkldexport
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

all: mkldexport

mkldexport: mkldexport.sh
	cp mkldexport.sh mkldexport
	chmod a+x mkldexport

clean:
	rm -f mkldexport
