#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/fmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= dfmgr.c fmgr.c 

