# $PostgreSQL$

subdir = contrib/rtree_gist
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = rtree_gist
DATA_built = rtree_gist.sql
DOCS = README.rtree_gist
REGRESS = rtree_gist

include $(top_srcdir)/contrib/contrib-global.mk
