# $PostgreSQL$

subdir = contrib/isbn_issn
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = isbn_issn
DATA_built = isbn_issn.sql
DOCS = README.isbn_issn

include $(top_srcdir)/contrib/contrib-global.mk
