#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/plan
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= createplan.c initsplan.c planmain.c planner.c \
	 setrefs.c
