#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/error
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= assert.c elog.c exc.c excabort.c excid.c format.c
