#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/file
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= fd.c
