# $Header$

subdir = contrib/intarray
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = _int
DATA_built = _int.sql
DOCS = README.intarray
REGRESS = _int

include $(top_srcdir)/contrib/contrib-global.mk
