#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/transam
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= transam.c transsup.c varsup.c xact.c xid.c 
