# $PostgreSQL$

subdir = contrib/earthdistance
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = earthdistance
DATA_built = earthdistance.sql
DOCS = README.earthdistance
REGRESS = earthdistance

include $(top_srcdir)/contrib/contrib-global.mk
