#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/heap
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= heapam.c hio.c stats.c
