# $PostgreSQL$

subdir = contrib/userlock
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = user_locks
DATA_built = user_locks.sql
DOCS = README.user_locks

include $(top_srcdir)/contrib/contrib-global.mk
