#!/bin/sh
#
# duplicate_oids
#
# $PostgreSQL$
#
# finds manually-assigned oids that are duplicated in the system tables.
#
# run this script in src/include/catalog.
#

FILES=`ls pg_*.h`

egrep '^DATA' $FILES | \
	sed -e 's/^.*OID[^=]*=[^0-9]*//' -e 's/[^0-9].*$//' | \
	sort -n | uniq -d | \
	egrep -v '^0*$'

exit 0
