#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/rtree (R-Tree access method)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= rtget.c rtproc.c rtree.c rtscan.c rtstrat.c
