# $PostgreSQL$

subdir = contrib/noupdate
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = noup
DATA_built = noup.sql
DOCS = README.noup

include $(top_srcdir)/contrib/contrib-global.mk
