#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/util
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= clauseinfo.c clauses.c indexnode.c internal.c plancat.c \
	joininfo.c keys.c ordering.c pathnode.c relnode.c tlist.c var.c
