# $PostgreSQL$

subdir = contrib/lo
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = lo
DATA_built = lo.sql
DATA = lo_drop.sql lo_test.sql
DOCS = README.lo

include $(top_srcdir)/contrib/contrib-global.mk
