#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/hash (hash access method)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= hash.c hashfunc.c hashinsert.c hashovfl.c hashpage.c hashscan.c \
	hashsearch.c hashstrat.c hashutil.c



