#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/sort
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= lselect.c psort.c
