#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for the main() of the postgres backend
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

VPATH:= $(VPATH):$(CURDIR)/main

SRCS_MAIN= main.c
