#-------------------------------------------------------------------------
#
# $Id$
#
#-------------------------------------------------------------------------
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= euc_tw_and_big5

SRCS += big5.c
OBJS += big5.o

include ../proc.mk
