#-------------------------------------------------------------------------
#
# Makefile
#    Makefile for doc directory to install man pages
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SRCDIR= ../../..
include ../../../Makefile.global

install: 
	-mkdir $(DESTDIR)$(POSTMANDIR)
	-mkdir $(DESTDIR)$(POSTMANDIR)/man3
	cp *.3* $(DESTDIR)$(POSTMANDIR)/man3
