#-------------------------------------------------------------------------
#
# Makefile
#    Makefile for doc directory to install man pages
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SRCDIR= ../../..
include ../../../Makefile.global

install: 
	-mkdir -p $(POSTMANDIR)
	-mkdir $(POSTMANDIR)/man3
	cp *.3* $(POSTMANDIR)/man3

