#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for regress/expected (the regression test)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

CLFILES=	create_function_1.out create_function_2.out copy.out constraints.out misc.out

clean:
	rm -f $(CLFILES)
