#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/lmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= lmgr.c lock.c multi.c proc.c single.c
