# $PostgreSQL$

subdir = contrib/pg_logger
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

PROGRAM = pg_logger
OBJS	= pg_logger.o

DOCS = README.pg_logger

include $(top_srcdir)/contrib/contrib-global.mk
