#
# Makefile for the storage manager subsystem
#
# $PostgreSQL$
#

subdir = src/backend/storage
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = buffer file freespace ipc large_object lmgr page smgr

include $(top_srcdir)/src/backend/common.mk
