#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/large_object
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= inv_api.c 
