#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/mmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= aset.c mcxt.c palloc.c portalmem.c oset.c

