#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/init
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= enbl.c findbe.c globals.c magic.c miscinit.c postinit.c
