#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/hash
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= dynahash.c hashfn.c
