#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/page
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= bufpage.c itemptr.c


