# $Header$

AROPT = crs

ifeq ($(with_gnu_ld), yes)
export_dynamic = -Wl,-E
rpath = -Wl,-rpath,$(libdir)
else
rpath = -Wl,-R$(libdir)
endif


DLSUFFIX = .so
ifeq ($(GCC), yes)
CFLAGS_SL = -fPIC
else
CFLAGS_SL = -KPIC
endif

%.so: %.o
	$(LD) -G -Bdynamic -o $@ $<
