# $Header$

AROPT = crs

ifeq ($(with_gnu_ld), yes)
export_dynamic = -Wl,-E
endif

DLSUFFIX = .so
ifeq ($(GCC), yes)
CFLAGS_SL = -fPIC
else
CFLAGS_SL = -KPIC
endif

%.so: %.o
	$(LD) -G -Bdynamic -o $@ $<
