/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 65536

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_acclist[366] =
    {   0,
       10,   10,    6,    6,   23,   23,   26,   26,    9,    9,
       27,   27,   18,   18,   77,   76,   24,   76,   76,   76,
       76,   76,   65,   76,   59,   65,   76,   59,   76,   24,
       65,   76,   48,   65,   76,   53,   65,   76,   57,   65,
       76,   58,   65,   76,   52,   65,   76,   55,   65,   76,
       51,   65,   76,   56,   65,   76,   65,   76,   54,   65,
       76,   39,   65,   76,16420,   50,   65,   76,   64,   65,
       76,   49,   65,   76,   49,   65,   76,   62,   65,   76,
       63,   65,   76,   60,   65,   76,   61,   65,   76,   45,
       76,   44,   45,   76,   44,   76,   33,   45,   76,   21,

       24,   45,   76,   31,   33,   45,   76,   31,   33,   45,
       76,   15,   45,   76,   31,   45,   76,   31,   33,   45,
       76,   31,   45,   76,   31,   33,   45,   76,   39,   45,
       76,16420,   31,   33,   45,   76,   43,   45,   76,16419,
       43,   45,   76,16419,   43,   45,   76,16419,   74,   76,
       73,   76,   73,   74,   76,   24,   74,   76,   74,   76,
       74,   76,   74,   76,   74,   76,   74,   75,   76,   71,
       76,   69,   71,   76,   71,   76,   71,   76,   71,   76,
       71,   76,   70,   76,   67,   76,   68,   76,   10,   76,
        8,   76,    3,    6,   76,    3,    6,   76,    3,   76,

        6,   76,   23,   76,   22,   76,   26,   76,   25,   76,
       26,   76,    9,   76,   14,   76,   27,   76,   28,   76,
       18,   76,   16,   76,   76,   40,16421,    4,   40,16421,
       48,   48,   48,   48,   39,16420,   40,16421,   40,16421,
       49,   49,   33,   33,   33,   34,   33,   33,    4,   33,
       33,   29,   33,   42,   43,16419,    7,   13,   74,   74,
       74,   40,   74,16421,    4,   74,   40,   74,16421,   68,
       10,    6,    6,    5,   23,   26,   26,   26,    9,   27,
       18,   17,   19,    4,    4,   40,16421,   48,   48,   47,
     8228,   40,16421,   41,16422,   49,   32,   30,   32,   30,

       32,   34,   30,    1,   33,   33,   30,   32,    4,   33,
        4,   33,    4,   33,   42, 8227,   74,   74,   74,    4,
       74,    4,   74,   40,   74,16421,   12,    5,   11,   20,
     8229,    2,    4,   49,   32,    2,    4,   33,   32,   42,
     8229,   74,   74,    2,    4,   74,    2,    2,    2,   48,
     8230,   49,   42,    2,   74,    2,   74,    2,   49,   46,
       49,   46,   46,   66,   72
    } ;

static yyconst short int yy_accept[273] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    4,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   19,
       20,   21,   22,   23,   25,   28,   30,   33,   36,   39,
       42,   45,   48,   51,   54,   57,   59,   62,   66,   69,
       72,   75,   78,   81,   84,   87,   90,   92,   95,   97,
      100,  104,  108,  112,  115,  118,  122,  125,  129,  133,
      137,  141,  145,  149,  151,  153,  156,  159,  161,  163,
      165,  167,  170,  172,  175,  177,  179,  181,  183,  185,
      187,  189,  191,  193,  196,  199,  201,  203,  205,  207,

      209,  211,  213,  215,  217,  219,  221,  223,  225,  226,
      226,  226,  228,  229,  231,  231,  232,  233,  234,  235,
      235,  237,  239,  239,  239,  239,  241,  241,  242,  243,
      244,  245,  245,  246,  247,  248,  248,  249,  251,  252,
      254,  255,  255,  255,  257,  258,  259,  260,  261,  262,
      265,  267,  270,  271,  272,  272,  272,  273,  274,  274,
      274,  275,  276,  277,  278,  279,  280,  280,  280,  281,
      282,  282,  282,  283,  284,  284,  284,  284,  285,  286,
      288,  289,  290,  290,  291,  292,  294,  294,  296,  297,
      298,  300,  303,  304,  304,  305,  306,  307,  309,  311,

      313,  315,  315,  315,  316,  317,  318,  319,  320,  322,
      324,  327,  327,  327,  328,  329,  329,  329,  330,  330,
      330,  331,  332,  332,  334,  334,  334,  334,  334,  335,
      336,  339,  340,  341,  343,  344,  347,  348,  349,  350,
      351,  352,  352,  353,  354,  356,  358,  359,  359,  359,
      360,  360,  360,  362,  362,  363,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  365,  365,
      366,  366
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    5,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    5,    5,   25,   26,   27,   28,   29,   30,
       25,   25,   31,   25,   25,   32,   25,   33,   25,   25,
       34,   25,   35,   25,   36,   25,   25,   37,   25,   25,
       38,   39,   40,    5,   25,    1,   25,   26,   27,   28,

       29,   30,   25,   25,   31,   25,   25,   32,   25,   33,
       25,   25,   34,   25,   35,   25,   36,   25,   25,   37,
       25,   25,   41,   22,   42,    5,    1,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    2,    3,    4,    5,    6,    5,    5,    5,    7,
        1,    1,    8,    5,    1,    9,   10,    5,   11,    5,
        1,    5,    5,    5,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
        1,    1
    } ;

static yyconst short int yy_base[302] =
    {   0,
        0,    4,   23,    0,   65,    0,  106,  126,  146,  166,
      186,    0,  597,  588,  219,  239,  589,  584,  107,  112,
      575,  570,  117,  137,  116,  121,  572, 1138, 1138,   97,
      552,  556,   98, 1138,    0,  154, 1138,  132, 1138, 1138,
     1138, 1138, 1138, 1138,  117,  549,  141,  262, 1138, 1138,
        0,  521, 1138, 1138, 1138, 1138, 1138, 1138, 1138,  540,
     1138,  175,  157, 1138,  193,  182,  266,  258,    0,  290,
      284,  326,  544,    0, 1138,    0,    0,  189,  533,  528,
      212,    0, 1138, 1138,  217,  518,  523,  221, 1138, 1138,
        0,    0,    9,    0,  338,  162,    0,    0, 1138,  495,

     1138,  168,    0,  247,  329, 1138,    0,  361,    0,  510,
      237,  364,  379,  375,  337,  257,  270,  522,  346,  505,
        0,  402,  516,  406,  397,  421,  356,    0,  487,  495,
      318,  425,  288,  490,  336,  340,  448,  468,  490,  491,
      121,  430,  501,  495, 1138, 1138,    0,  477,  357,  519,
      537,  524,    0,    0,  440,  560,    0,    0,  168,  481,
      445,    0,  450,  219,  448,    0,  476,  563,  498,    0,
      529,  572, 1138, 1138,  575,  567,  472,  592,  465,  615,
      585,  590,  471, 1138, 1138,  619,  450,  623,  436, 1138,
     1138,  441, 1138,  456, 1138,    0,  379,  451,    0,  434,

      398,  421,    0,  267, 1138,  641,  633,  288,  661,  420,
      657,  684,  687, 1138,  545,  696,  699, 1138,  708,  711,
     1138, 1138,  254,  600,  651,  720,  723,  714,  732,  417,
      738,  399,  365,    0,  417,  742,  745,  748,  751,  760,
     1138,  766,  373,  373,  769,  772,  775,  784,  366,  341,
      335,  306,    0,  279,  787, 1138,  408,  273,  256,  250,
      248,  214,  198,  177,  164,  164,  138, 1138,   82, 1138,
     1138,  819,  832,  845,  858,  871,  884,  897,  910,  923,
      936,  939,  947,  955,  967,  970,  982,  995, 1004, 1013,
     1026, 1039, 1052, 1064, 1077, 1090, 1103, 1108, 1120,    2,

     1125
    } ;

static yyconst short int yy_def[302] =
    {   0,
      272,  272,  271,    3,  271,    5,  273,  273,  274,  274,
      272,   11,  275,  275,  276,  276,  277,  277,  278,  278,
      279,  279,  272,  272,  280,  280,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  281,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      282,  282,  271,  271,  271,  271,  271,  271,  271,  283,
      271,  283,   62,  271,  271,   62,  271,   62,   48,  271,
      284,  284,   72,  285,  271,  285,  285,  285,  285,  285,
      285,  285,  271,  271,  271,  271,  271,  271,  271,  271,
      286,  287,  271,  288,  288,  289,   95,  290,  271,  291,

      271,  291,  292,  271,  271,  271,  293,  271,  294,  271,
      271,  271,  295,  271,  271,  281,  281,  271,  281,  271,
       48,  271,  296,  271,  271,  271,  271,  282,  282,  283,
      283,  271,  131,  271,  131,  271,  297,  295,  297,  283,
      298,  271,  271,   72,  271,  271,  285,  285,  285,  285,
      299,  285,  286,  287,  271,  271,  288,   95,  289,  289,
      289,  290,  291,  291,  291,  292,  271,  271,  271,  293,
      271,  271,  271,  271,  271,  271,  295,  295,  178,  271,
      281,  271,  296,  271,  271,  271,  271,  271,  282,  271,
      271,  271,  271,  297,  271,  139,  139,  297,  138,  138,

      138,  271,  300,  298,  271,  285,  285,  299,  299,  209,
      285,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  295,  178,  271,  271,  271,  271,  282,  297,
      138,  295,  301,  285,  299,  209,  295,  295,  271,  271,
      271,  271,  282,  301,  299,  299,  271,  271,  271,  282,
      271,  271,  282,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
        0,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271
    } ;

static yyconst short int yy_nxt[1181] =
    {   0,
      271,  115,  115,  115,  271,   29,  116,  271,  271,   29,
      155,  156,  155,  233,  271,   30,   31,   32,   33,   30,
       31,   32,   33,   34,   35,   36,   35,   34,   37,   38,
       34,   39,   34,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   34,   49,   34,   50,   34,   51,   51,   51,
       51,   52,   51,   51,   51,   51,   51,   51,   51,   51,
       53,   34,   54,   55,   56,   57,   58,   59,   58,   60,
       61,   60,   62,   63,   64,   65,   65,   63,   63,   65,
       66,   67,   68,   69,   70,   65,   63,   63,   63,   71,
       72,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   73,   65,   57,   65,   57,   57,   75,   75,   76,
      270,   77,  101,  110,  114,  111,  111,  101,  105,  105,
      105,   78,   79,   80,   81,  108,   82,   75,   75,   76,
      108,   77,  106,  120,  118,  121,  202,  203,  105,  105,
      105,   78,   79,   80,   81,  102,   82,   84,   84,   84,
      102,   29,  106,  113,  109,  115,  115,  115,  123,  109,
      116,   85,   86,   87,   88,  269,   89,   84,   84,   84,
      119,   29,  135,  165,  159,  271,  132,  132,  132,  161,
      159,   85,   86,   87,   88,  161,   89,   90,   90,   90,
      133,   29,  268,  134,  132,  132,  132,  137,  120,  267,

      121,   30,   31,   32,   33,  148,  164,  149,  136,  266,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   95,  165,   95,   95,   95,  152,  265,
      149,   96,   95,  110,   95,  111,   97,  114,   95,  111,
       95,   95,   95,   95,  264,   95,   95,   95,  167,  168,
      167,   96,   95,  114,   95,  111,   97,  164,   95,  118,
       95,   95,   95,  124,  124,  124,  223,  132,  132,  132,
      138,  237,  118,  135,  263,  139,  271,  125,  126,  262,
      121,  136,  202,  203,  122,  142,  142,  142,  261,  177,
      127,  132,  132,  132,  130,  119,  130,  130,  130,  143,

      235,  260,  130,  130,  191,  135,  192,  130,  119,  140,
      256,  130,  130,  130,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  142,  142,  142,
      169,  169,  169,  131,  190,  145,  190,  255,  115,  115,
      115,  143,  158,  116,  158,  158,  158,  181,  182,  181,
      159,  158,  191,  158,  191,  158,  193,  158,  193,  158,
      158,  158,  171,  172,  171,  175,  175,  175,  254,  187,
      173,  187,  253,  152,  188,  149,  175,  175,  175,  176,
      202,  203,  112,  178,  119,  178,  178,  178,  202,  203,
      176,  179,  178,  180,  178,  230,  178,  230,  178,  252,

      178,  178,  178,  175,  175,  175,  250,  124,  124,  124,
      185,  223,  185,  185,  232,  185,  232,  176,  177,  195,
      122,  125,  175,  175,  175,  185,  132,  132,  132,  235,
      127,  142,  142,  142,  245,  258,  176,  236,  259,  186,
      136,  155,  156,  155,  203,  143,  215,  215,  215,  127,
      195,  231,  196,  195,  196,  196,  196,  159,  195,  134,
      196,  196,  229,  197,  198,  196,  198,  196,  188,  196,
      196,  196,  199,  184,  199,  199,  199,  167,  168,  167,
      200,  199,  224,  201,  223,  199,  164,  199,  164,  199,
      199,  199,  195,  159,  196,  150,  196,  196,  196,  169,

      169,  169,  196,  196,  271,  197,  131,  196,  134,  196,
      131,  196,  196,  196,  205,  189,  205,  205,  184,  205,
      175,  175,  206,  122,  118,  175,  175,  206,  112,  205,
      171,  172,  171,  164,  207,  113,  112,  150,  177,  207,
      151,  209,  211,  209,  209,  209,  215,  215,  215,  210,
      209,  150,  209,  146,  209,  131,  209,  129,  209,  209,
      209,  212,  213,  212,  216,  217,  216,  122,  113,  214,
      112,  271,  218,  219,  220,  219,  175,  175,  175,  104,
      222,  221,  222,  222,  104,  222,  181,  182,  181,   99,
      176,  225,  182,  225,   99,  222,  178,   93,  178,  178,

      178,  238,  239,  238,  179,  178,   93,  178,  271,  178,
      271,  178,  271,  178,  178,  178,  175,  175,  175,  271,
      175,  175,  175,  119,  227,  227,  227,  271,  226,  271,
      176,  271,  271,  180,  176,  271,  271,  186,  228,  271,
      271,  188,  175,  175,  206,  271,  234,  127,  234,  234,
      271,  234,  225,  240,  225,  271,  207,  271,  175,  175,
      206,  234,  177,  271,  271,  209,  271,  209,  209,  209,
      271,  271,  207,  210,  209,  211,  209,  271,  209,  271,
      209,  271,  209,  209,  209,  212,  213,  212,  212,  213,
      212,  271,  271,  214,  271,  271,  214,  216,  217,  216,

      216,  217,  216,  271,  271,  218,  271,  271,  218,  219,
      220,  219,  219,  220,  219,  271,  271,  221,  271,  271,
      221,  225,  240,  225,  227,  227,  227,  241,  271,  241,
      241,  271,  241,  242,  242,  242,  271,  271,  228,  238,
      239,  238,  241,  238,  239,  246,  238,  239,  238,  238,
      239,  238,  247,  239,  247,  271,  271,  223,  271,  271,
      223,  225,  182,  225,  271,  271,  243,  248,  248,  248,
      238,  239,  246,  238,  239,  246,  247,  239,  247,  271,
      271,  235,  271,  271,  235,  248,  248,  248,  257,  257,
      257,  271,  271,  271,  271,  271,  271,  271,  226,  271,

      249,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  251,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   94,   94,   94,   94,   94,   94,   94,   94,   94,
       94,   94,   94,   94,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,   98,   98,  100,  100,  100,

      100,  100,  100,  100,  100,  100,  100,  100,  100,  100,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  103,
      103,  103,  103,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  117,  117,  117,  117,  128,
      128,  130,  271,  271,  130,  130,  144,  144,  144,  271,
      271,  271,  271,  144,  271,  144,  144,  147,  271,  271,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      153,  153,  154,  154,  154,  154,  154,  154,  271,  154,
      154,  154,  154,  154,  154,  157,  157,  157,  157,  157,

      157,  157,  271,  157,  157,  157,  157,  157,  160,  271,
      271,  160,  160,  162,  162,  162,  162,  162,  271,  162,
      162,  162,  162,  162,  162,  162,  163,  163,  163,  163,
      163,  271,  163,  163,  163,  163,  163,  163,  163,  166,
      166,  166,  166,  166,  166,  271,  166,  166,  166,  166,
      166,  166,  170,  170,  170,  170,  170,  170,  271,  170,
      170,  170,  170,  170,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  174,  177,  177,  271,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  194,  194,  194,  194,  194,  194,  194,
      194,  194,  194,  194,  194,  194,  204,  204,  204,  204,
      208,  208,  271,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  244,  244,  244,  244,   27,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271
    } ;

static yyconst short int yy_chk[1181] =
    {   0,
        0,   35,   35,   35,    0,    1,   35,    0,    0,    2,
       93,   93,   93,  300,    0,    1,    1,    1,    1,    2,
        2,    2,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    7,    7,    7,
      269,    7,   19,   30,   33,   30,   33,   20,   23,   23,
       23,    7,    7,    7,    7,   25,    7,    8,    8,    8,
       26,    8,   23,   45,   38,   45,  141,  141,   24,   24,
       24,    8,    8,    8,    8,   19,    8,    9,    9,    9,
       20,    9,   24,   47,   25,   36,   36,   36,   47,   26,
       36,    9,    9,    9,    9,  267,    9,   10,   10,   10,
       38,   10,   63,  102,   96,   63,   62,   62,   62,   96,
      159,   10,   10,   10,   10,  159,   10,   11,   11,   11,
       62,   11,  266,   62,   65,   65,   65,   66,   66,  265,

       66,   11,   11,   11,   11,   78,  102,   78,   65,  264,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   15,  164,   15,   15,   15,   81,  263,
       81,   15,   15,   85,   15,   85,   15,   88,   15,   88,
       15,   15,   15,   16,  262,   16,   16,   16,  104,  104,
      104,   16,   16,  111,   16,  111,   16,  164,   16,  116,
       16,   16,   16,   48,   48,   48,  223,   67,   67,   67,
       68,  223,  117,   68,  261,   68,   68,   48,   48,  260,
       48,   67,  204,  204,   67,   71,   71,   71,  259,  208,
       48,   70,   70,   70,   70,  116,   70,   70,   70,   71,

      208,  258,   70,   70,  133,   70,  133,   70,  117,   70,
      254,   70,   70,   70,   70,   70,   70,   70,   70,   70,
       70,   70,   70,   70,   70,   70,   70,   72,   72,   72,
      105,  105,  105,  131,  131,   72,  131,  252,  115,  115,
      115,   72,   95,  115,   95,   95,   95,  119,  119,  119,
       95,   95,  135,   95,  135,   95,  136,   95,  136,   95,
       95,   95,  108,  108,  108,  112,  112,  112,  251,  127,
      108,  127,  250,  149,  127,  149,  114,  114,  114,  112,
      233,  233,  112,  113,  119,  113,  113,  113,  244,  244,
      114,  113,  113,  114,  113,  197,  113,  197,  113,  249,

      113,  113,  113,  122,  122,  122,  243,  124,  124,  124,
      125,  232,  125,  125,  201,  125,  201,  122,  235,  230,
      122,  124,  126,  126,  126,  125,  132,  132,  132,  235,
      122,  142,  142,  142,  235,  257,  126,  210,  257,  126,
      132,  155,  155,  155,  202,  142,  161,  161,  161,  126,
      137,  200,  137,  198,  137,  137,  137,  161,  194,  192,
      137,  137,  189,  137,  137,  137,  137,  137,  187,  137,
      137,  137,  138,  183,  138,  138,  138,  167,  167,  167,
      138,  138,  179,  138,  177,  138,  165,  138,  163,  138,
      138,  138,  139,  160,  139,  148,  139,  139,  139,  169,

      169,  169,  139,  139,  144,  139,  140,  139,  134,  139,
      130,  139,  139,  139,  143,  129,  143,  143,  123,  143,
      150,  150,  150,  120,  118,  152,  152,  152,  110,  143,
      171,  171,  171,  100,  150,   87,   86,  150,  151,  152,
       80,  151,  152,  151,  151,  151,  215,  215,  215,  151,
      151,   79,  151,   73,  151,   60,  151,   52,  151,  151,
      151,  156,  156,  156,  168,  168,  168,   46,   32,  156,
       31,   27,  168,  172,  172,  172,  175,  175,  175,   22,
      176,  172,  176,  176,   21,  176,  181,  181,  181,   18,
      175,  182,  182,  182,   17,  176,  178,   14,  178,  178,

      178,  224,  224,  224,  178,  178,   13,  178,    0,  178,
        0,  178,    0,  178,  178,  178,  180,  180,  180,    0,
      186,  186,  186,  181,  188,  188,  188,    0,  182,    0,
      180,    0,    0,  180,  186,    0,    0,  186,  188,    0,
        0,  188,  206,  206,  206,    0,  207,  186,  207,  207,
        0,  207,  225,  225,  225,    0,  206,    0,  211,  211,
      211,  207,  209,    0,    0,  209,    0,  209,  209,  209,
        0,    0,  211,  209,  209,  211,  209,    0,  209,    0,
      209,    0,  209,  209,  209,  212,  212,  212,  213,  213,
      213,    0,    0,  212,    0,    0,  213,  216,  216,  216,

      217,  217,  217,    0,    0,  216,    0,    0,  217,  219,
      219,  219,  220,  220,  220,    0,    0,  219,    0,    0,
      220,  226,  226,  226,  227,  227,  227,  228,    0,  228,
      228,    0,  228,  229,  229,  229,    0,    0,  227,  231,
      231,  231,  228,  236,  236,  236,  237,  237,  237,  238,
      238,  238,  239,  239,  239,    0,    0,  237,    0,    0,
      238,  240,  240,  240,    0,    0,  229,  242,  242,  242,
      245,  245,  245,  246,  246,  246,  247,  247,  247,    0,
        0,  245,    0,    0,  246,  248,  248,  248,  255,  255,
      255,    0,    0,    0,    0,    0,    0,    0,  240,    0,

      242,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  248,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  273,  273,  273,  273,  273,  273,  273,  273,
      273,  273,  273,  273,  273,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  275,  275,  275,
      275,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  279,  279,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  281,  281,  281,  281,
      281,  281,  281,  281,  281,  281,  281,  281,  281,  282,
      282,  283,    0,    0,  283,  283,  284,  284,  284,    0,
        0,    0,    0,  284,    0,  284,  284,  285,    0,    0,
      285,  285,  285,  285,  285,  285,  285,  285,  285,  285,
      286,  286,  287,  287,  287,  287,  287,  287,    0,  287,
      287,  287,  287,  287,  287,  288,  288,  288,  288,  288,

      288,  288,    0,  288,  288,  288,  288,  288,  289,    0,
        0,  289,  289,  290,  290,  290,  290,  290,    0,  290,
      290,  290,  290,  290,  290,  290,  291,  291,  291,  291,
      291,    0,  291,  291,  291,  291,  291,  291,  291,  292,
      292,  292,  292,  292,  292,    0,  292,  292,  292,  292,
      292,  292,  293,  293,  293,  293,  293,  293,    0,  293,
      293,  293,  293,  293,  294,  294,  294,  294,  294,  294,
      294,  294,  294,  294,  294,  294,  294,  295,  295,    0,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  298,  298,  298,  298,
      299,  299,    0,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  301,  301,  301,  301,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pgc.l"
#define INITIAL 0
/* This is a modified version of src/backend/parser/scan.l */
#line 3 "pgc.l"
#include "config.h"

#include <ctype.h>
#include <sys/types.h>
#include <limits.h>

#ifndef PATH_MAX
#include <sys/param.h>
#define PATH_MAX MAXPATHLEN
#endif

#if defined(HAVE_STRING_H)
#include <string.h>
#else
#include <strings.h>
#endif
#include <errno.h>

#include "postgres.h"
#include "miscadmin.h"
#include "nodes/pg_list.h"
#include "nodes/parsenodes.h"
#include "parser/gramparse.h"
#include "parser/scansup.h"
#include "extern.h"
#include "preproc.h"
#include "utils/builtins.h"

#ifdef  YY_READ_BUF_SIZE
#undef  YY_READ_BUF_SIZE
#endif
#define YY_READ_BUF_SIZE	MAX_PARSE_BUFFER

/* some versions of lex define this as a macro */
#if defined(yywrap)
#undef yywrap
#endif /* yywrap */

extern YYSTYPE yylval;
int llen;
char literal[MAX_PARSE_BUFFER];
int before_comment;

struct _yy_buffer { YY_BUFFER_STATE 	buffer;
		    long		lineno;
		    char	      * filename;
		    struct _yy_buffer * next;
		  } *yy_buffer = NULL;

struct _defines *defines = NULL;
static char *old;

#define C 1
#define SQL 2
#define incl 3
#define def 4
#define def_ident 5

/* OK, here is a short description of lex/flex rules behavior.
 * The longest pattern which matches an input string is always chosen.
 * For equal-length patterns, the first occurring in the rules list is chosen.
 * INITIAL is the starting condition, to which all non-conditional rules apply.
 * When in an exclusive condition, only those rules defined for that condition apply.
 *
 * Exclusive states change parsing rules while the state is active.
 * There are exclusive states for quoted strings, extended comments,
 *  and to eliminate parsing troubles for numeric strings.
 * Exclusive states:
 *  <xb> binary numeric string - thomas 1997-11-16
 *  <xc> extended C-style comments - tgl 1997-07-12
 *  <xd> delimited identifiers (double-quoted identifiers) - tgl 1997-10-27
 *  <xh> hexadecimal numeric string - thomas 1997-11-16
 *  <xm> numeric strings with embedded minus sign - tgl 1997-09-05
 *  <xq> quoted strings - tgl 1997-07-30
 *
 * The "extended comment" syntax closely resembles allowable operator syntax.
 * So, when in condition <xc>, only strings which would terminate the
 *  "extended comment" trigger any action other than "ignore".
 * Be sure to match _any_ candidate comment, including those with appended
 *	operator-like symbols. - thomas 1997-07-14
 */
#define xb 6

#define xc 7

#define xd 8

#define xdc 9

#define xh 10

#define xm 11

#define xq 12

/* Binary number
 */
/* Hexadecimal number
 */
/* Extended quote
 * xqdouble implements SQL92 embedded quote
 * xqcat allows strings to cross input lines
 */
/* Delimited quote
 * Allows embedded spaces and other special characters into identifiers.
 */
/* Comments
 * Ignored by the scanner and parser.
 */
/*
real			[\-]?(((({digit}*\.{digit}+)|({digit}+\.{digit}*))([Ee][-+]?{digit}+)?)|({digit}+[Ee][-+]?{digit}+))
*/
/* some stuff needed for ecpg */
/* DO NOT PUT ANY COMMENTS IN THE FOLLOWING SECTION.
 * AT&T lex does not properly handle C-style comments in this second lex block.
 * So, put comments here. tgl - 1997-09-08
 *
 * Quoted strings must allow some special characters such as single-quote
 *  and newline.
 * Embedded single-quotes are implemented both in the SQL/92-standard
 *  style of two adjacent single quotes "''" and in the Postgres/Java style
 *  of escaped-quote "\'".
 * Other embedded escaped characters are matched explicitly and the leading
 *  backslash is dropped from the string. - thomas 1997-09-24
 */
#line 904 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 186 "pgc.l"

#line 1057 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 272 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1138 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 187 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 189 "pgc.l"
{ ECHO; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 191 "pgc.l"
{ ECHO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 192 "pgc.l"
{
				before_comment = YYSTATE;
				ECHO;
	 			BEGIN(xc);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 198 "pgc.l"
{ ECHO; BEGIN(before_comment); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 200 "pgc.l"
{ ECHO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 202 "pgc.l"
{
					BEGIN(xb);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 207 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,2);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad binary integer input!");
					return ICONST;
				}
	YY_BREAK
case 9:
#line 218 "pgc.l"
case 10:
YY_RULE_SETUP
#line 218 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 11:
#line 225 "pgc.l"
case 12:
YY_RULE_SETUP
#line 225 "pgc.l"
{
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 228 "pgc.l"
{
					BEGIN(xh);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 233 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,16);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad hexadecimal integer input");
					return ICONST;
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 244 "pgc.l"
{
					BEGIN(xq);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 249 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(scanstr(literal));
					return SCONST;
				}
	YY_BREAK
case 17:
#line 255 "pgc.l"
case 18:
#line 256 "pgc.l"
case 19:
YY_RULE_SETUP
#line 256 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 262 "pgc.l"
{
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 266 "pgc.l"
{
					BEGIN(xd);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 271 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 276 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 282 "pgc.l"
{
					BEGIN(xdc);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 287 "pgc.l"
{
					BEGIN(C);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 292 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 299 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 300 "pgc.l"
{
					BEGIN(SQL);
					return yytext[0];
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 306 "pgc.l"
{ 	return TYPECAST; }
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 307 "pgc.l"
{
					BEGIN(xm);
					return yytext[0];
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 311 "pgc.l"
{ /* 
				   * We may find a ';' inside a structure
				   * definition in a TYPE or VAR statement.
				   * This is not an EOL marker.
				   */
				  if (yytext[0] == ';' && struct_level == 0)
					 BEGIN C;
				  return yytext[0];
				}
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 320 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 324 "pgc.l"
{
					if (strcmp((char*)yytext,"!=") == 0)
						yylval.str = mm_strdup("<>"); /* compatability */
					else
						yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 331 "pgc.l"
{
					yylval.ival = atoi((char*)&yytext[1]);
					return PARAM;
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 335 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					BEGIN(xm);
					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 388 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
#if 0
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
#endif
						yylval.str = mm_strdup((char*)yytext);
                                                return SCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 409 "pgc.l"
{
                                        char* endptr;

                                        BEGIN(xm);
                                        if (strlen((char *)yytext) <= 17)
                                        {
                                                errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad float8 input");
						return FCONST;
                                        }
                                        yylval.str = mm_strdup((char*)yytext);
                                        return SCONST;
                                }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 425 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.dval = strtod(((char *)yytext),&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float8 input");
					return FCONST;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 435 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
#if 0
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
#endif
						yylval.str = mm_strdup((char*)yytext);
                                                return SCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 455 "pgc.l"
{
                                        char* endptr;

                                        if (strlen((char *)yytext) <= 17)
                                        {
                                                errno = 0;
                                                yylval.dval = strtod((char *)yytext,&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad float8 input");
						return FCONST;
                                        }
                                        yylval.str = mm_strdup((char*)yytext);
                                        return SCONST;
                                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 469 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.dval = strtod((char *)yytext,&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float input");
					return FCONST;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 478 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext+1);
					return(CVARIABLE);
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 482 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 534 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 535 "pgc.l"
{ return yytext[0]; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 536 "pgc.l"
{ BEGIN SQL; return SQL_START; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 537 "pgc.l"
{ /* ignore */ } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 538 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return(CPP_LINE);
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 542 "pgc.l"
{
					ScanKeyword		*keyword;

					keyword = ScanCKeywordLookup((char*)yytext);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						struct _defines *ptr;

						for (ptr = defines; ptr; ptr = ptr->next)
						{
							if (strcmp(yytext, ptr->old) == 0)
							{
								struct _yy_buffer *yb;

								yb = mm_alloc(sizeof(struct _yy_buffer));

					                        yb->buffer =  YY_CURRENT_BUFFER;
					                        yb->lineno = yylineno;
					                        yb->filename = mm_strdup(input_filename);
					                        yb->next = yy_buffer;

					                        yy_buffer = yb;

								yy_scan_string(ptr->new);
								break;
							}
						}
						if (ptr == NULL) 
						{
							yylval.str = mm_strdup((char*)yytext);
							return IDENT;
						}
					}
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 579 "pgc.l"
{ return(';'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 580 "pgc.l"
{ return(','); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 581 "pgc.l"
{ return('*'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 582 "pgc.l"
{ return('%'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 583 "pgc.l"
{ return('/'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 584 "pgc.l"
{ return('+'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 585 "pgc.l"
{ return('-'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 586 "pgc.l"
{ return('('); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 587 "pgc.l"
{ return(')'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 588 "pgc.l"
{ ECHO; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 589 "pgc.l"
{ return('{'); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 590 "pgc.l"
{ return('}'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 591 "pgc.l"
{ return('['); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 592 "pgc.l"
{ return(']'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 593 "pgc.l"
{ return('='); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 594 "pgc.l"
{ return S_ANYTHING; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 595 "pgc.l"
{BEGIN(def_ident);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 596 "pgc.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 597 "pgc.l"
{
				old = mm_strdup(yytext);
				BEGIN(def);
				llen = 0;
				*literal = '\0';
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 603 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 604 "pgc.l"
{
				struct _defines *ptr, *this;
        
                                for (ptr = defines; ptr != NULL; ptr = ptr->next)
                                {
                                     if (strcmp(old, ptr->old) == 0)
                                     {
					free(ptr->new);
					ptr->new = mm_strdup(scanstr(literal));
                                     }
                                }
				if (ptr == NULL)
				{                        
                                        this = (struct _defines *) mm_alloc(sizeof(struct _defines));

                                        /* initial definition */
                                        this->old = old;
                                        this->new = mm_strdup(scanstr(literal));
					this->next = defines;
					defines = this;
				}

				BEGIN(C);
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 628 "pgc.l"
{
				if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
					yyerror("ERROR: define statement parse buffer exceeded");
				memcpy(literal+llen, yytext, yyleng+1);
				llen += yyleng;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 634 "pgc.l"
{ BEGIN(incl); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 635 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 636 "pgc.l"
{ /* got the include file name */
			  struct _yy_buffer *yb;
			  struct _include_path *ip;
			  char inc_file[PATH_MAX];

			  yb = mm_alloc(sizeof(struct _yy_buffer));

			  yb->buffer =  YY_CURRENT_BUFFER;
			  yb->lineno = yylineno;
			  yb->filename = input_filename;
			  yb->next = yy_buffer;

			  yy_buffer = yb;

			  if (yytext[strlen(yytext) - 1] == ';')
				yytext[strlen(yytext) - 1] = '\0';

			  yyin = NULL;
			  for (ip = include_paths; yyin == NULL && ip != NULL; ip = ip->next)
			  {
				if (strlen(ip->path) + strlen(yytext) + 3 > PATH_MAX)
				{
					fprintf(stderr, "Error: Path %s/%s is too long in line %d, skipping.\n", ip->path, yytext, yylineno);
					continue;
				}
			  	sprintf (inc_file, "%s/%s", ip->path, yytext);
		          	yyin = fopen( inc_file, "r" );
			  	if (!yyin)
				{
					if (strcmp(inc_file + strlen(inc_file) - 2, ".h"))
					{
						strcat(inc_file, ".h");
						yyin = fopen( inc_file, "r" );
					}

				}
			  }
			  if (!yyin)
			  {
				fprintf(stderr, "Error: Cannot open include file %s in line %d\n", yytext, yylineno);
				exit(NO_INCLUDE_FILE); 
			  }

			  input_filename = mm_strdup(inc_file);
			  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE ));
			  yylineno = 0;
			  output_line_number();

			  BEGIN C;
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 686 "pgc.l"
{ BEGIN C; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C):
case YY_STATE_EOF(SQL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(def):
case YY_STATE_EOF(def_ident):
case YY_STATE_EOF(xb):
case YY_STATE_EOF(xc):
case YY_STATE_EOF(xd):
case YY_STATE_EOF(xdc):
case YY_STATE_EOF(xh):
case YY_STATE_EOF(xm):
case YY_STATE_EOF(xq):
#line 687 "pgc.l"
{ if (yy_buffer == NULL)
				yyterminate();
			  else
			  {
				struct _yy_buffer *yb = yy_buffer;

				if (yyin != NULL)
					fclose(yyin);

				yy_delete_buffer( YY_CURRENT_BUFFER );
				yy_switch_to_buffer(yy_buffer->buffer);

				yylineno = yy_buffer->lineno;

				free(input_filename);
				input_filename = yy_buffer->filename;

				yy_buffer = yy_buffer->next;
				free(yb);
				output_line_number();
			  }
			}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 709 "pgc.l"
ECHO;
	YY_BREAK
#line 1994 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 272 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 272 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 271);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 709 "pgc.l"

void
lex_init(void)
{
    braces_open = 0;
    BEGIN C;
}

int yywrap(void) 
{ 
    return 1;
}
