/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 65536

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
static yyconst short int yy_acclist[327] =
    {   0,
       10,   10,    6,    6,   23,   23,   26,   26,    9,    9,
       27,   27,   18,   18,   75,   74,   24,   74,   74,   63,
       74,   57,   63,   74,   57,   74,   24,   63,   74,   46,
       63,   74,   51,   63,   74,   55,   63,   74,   56,   63,
       74,   50,   63,   74,   53,   63,   74,   49,   63,   74,
       54,   63,   74,   63,   74,   52,   63,   74,   38,   63,
       74,16420,   48,   63,   74,   62,   63,   74,   47,   63,
       74,   47,   63,   74,   60,   63,   74,   61,   63,   74,
       58,   63,   74,   59,   63,   74,   43,   74,   42,   43,
       74,   42,   74,   33,   43,   74,   21,   24,   43,   74,

       31,   33,   43,   74,   31,   33,   43,   74,   15,   43,
       74,   31,   43,   74,   31,   33,   43,   74,   31,   43,
       74,   31,   33,   43,   74,   38,   43,   74,16420,   31,
       33,   43,   74,   41,   43,   74,16419,   41,   43,   74,
    16419,   41,   43,   74,16419,   72,   74,   71,   74,   71,
       72,   74,   24,   72,   74,   72,   74,   72,   73,   74,
       69,   74,   67,   69,   74,   69,   74,   68,   74,   65,
       74,   66,   74,   10,   74,    8,   74,    3,    6,   74,
        3,    6,   74,    3,   74,    6,   74,   23,   74,   22,
       74,   26,   74,   25,   74,    9,   74,   14,   74,   27,

       74,   28,   74,   18,   74,   16,   74,   74,    4,   46,
       46,   46,   46,   38,16420,   39,16421,   39,16421,   47,
       47,   33,   33,   33,   34,   33,   33,    4,   33,   33,
       29,   33,   40,   41,16419,    7,   13,   72,    4,   72,
       66,   10,    6,    6,    5,   23,   26,    9,   27,   18,
       17,   19,    4,    4,   46,   46,   45, 8228,   39,16421,
       39,16421,   47,   32,   30,   32,   30,   32,   34,   30,
        1,   33,   33,   30,   32,    4,   33,    4,   33,    4,
       33,   40, 8227,   72,    4,   72,    4,   72,   12,    5,
       11,   20,    2,    4, 8229,   39,16421,   47,   32,    2,

        4,   33,   32,   40,   72,    2,    4,   72,    2,    2,
        2,   46,   47,   40,    2,   72,    2,   72,    2,   47,
       44,   47,   44,   44,   64,   70
    } ;

static yyconst short int yy_accept[248] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    4,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   19,
       20,   22,   25,   27,   30,   33,   36,   39,   42,   45,
       48,   51,   54,   56,   59,   63,   66,   69,   72,   75,
       78,   81,   84,   87,   89,   92,   94,   97,  101,  105,
      109,  112,  115,  119,  122,  126,  130,  134,  138,  142,
      146,  148,  150,  153,  156,  158,  161,  163,  166,  168,
      170,  172,  174,  176,  178,  181,  184,  186,  188,  190,
      192,  194,  196,  198,  200,  202,  204,  206,  208,  209,

      210,  210,  211,  212,  213,  214,  214,  216,  218,  218,
      218,  218,  220,  220,  221,  222,  223,  224,  224,  225,
      226,  227,  227,  228,  230,  231,  233,  234,  234,  234,
      236,  237,  238,  239,  241,  242,  243,  243,  243,  244,
      245,  245,  245,  246,  247,  248,  249,  249,  249,  250,
      251,  251,  251,  252,  253,  253,  254,  255,  256,  257,
      257,  257,  257,  257,  258,  259,  261,  261,  263,  264,
      265,  267,  270,  271,  271,  272,  273,  274,  276,  278,
      280,  282,  282,  282,  283,  284,  285,  287,  289,  289,
      289,  290,  291,  291,  291,  292,  292,  292,  293,  293,

      295,  295,  295,  296,  296,  298,  299,  300,  303,  304,
      305,  306,  309,  310,  311,  312,  313,  313,  314,  315,
      317,  319,  320,  320,  320,  321,  321,  321,  323,  323,
      324,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  326,  326,  327,  327
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    5,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    5,    5,   25,   26,   27,   28,   29,   30,
       25,   25,   31,   25,   25,   32,   25,   33,   25,   25,
       34,   25,   35,   25,   36,   25,   25,   37,   25,   25,
       38,   39,   40,    5,   25,    1,   25,   26,   27,   28,

       29,   30,   25,   25,   31,   25,   25,   32,   25,   33,
       25,   25,   34,   25,   35,   25,   36,   25,   25,   37,
       25,   25,   41,   22,   42,    5,    1,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,

       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25
    } ;

static yyconst int yy_meta[43] =
    {   0,
        1,    2,    3,    4,    5,    6,    5,    5,    5,    7,
        1,    1,    8,    5,    1,    9,   10,    5,   11,    5,
        1,    5,    5,    5,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,    1,   13,    1,
        1,    1
    } ;

static yyconst short int yy_base[277] =
    {   0,
        0,    1,   19,    0,   61,    0,  102,  107,  112,  132,
      152,    0,  518,  516,  185,  205,  518,  509,  506,  505,
      491,  489,    0,  141,  102,  107,  497, 1038, 1038,  482,
     1038,    6,  145, 1038,  121, 1038, 1038, 1038, 1038, 1038,
     1038,  102,  467,  109,  228, 1038, 1038,    0,  447, 1038,
     1038, 1038, 1038, 1038, 1038, 1038,  463, 1038,  232,  110,
     1038,  159,  123,  236,  153,    0,  256,  292,  295,  468,
        0, 1038,    0,    0,  457,    0, 1038, 1038,  454, 1038,
     1038,    0,    0,  193,    0,  307,  119,    0,    0, 1038,
        0, 1038,    0,  213,  239, 1038,    0,  299,    0,  327,

      264,  128,  161,  459,  315,  441,    0,  353,  455,  357,
      348,  372,  323,    0,  427,  431,  157,  376,  185,  426,
      203,  207,  399,  419,  441,  424,  233,  381,  452,  428,
     1038, 1038,    0,  480,    0,    0,  391,  470,    0,    0,
      193,  423,  396,    0,    0,    0,  427,  473,  449,    0,
      488,  503, 1038, 1038,  421,  509,  407,  506,  517,  532,
      523,  352,  417, 1038, 1038,  547,  395,  551,  384, 1038,
     1038,  391, 1038,  402, 1038,    0,  237,  400,    0,  378,
      256,  363,    0,  290, 1038,  311,  575,  345,  555,  558,
     1038,  569,  598,  601, 1038,  610,  613, 1038,  315,  583,

      622,  625, 1038,  339,  628,  631,  345,  634,  333,  336,
      368,  637,  646,  649,  652,  661,  666,  310,  373,  669,
      672,  675,  684,  304,  294,  288,  278,    0,  272,  687,
     1038,  137,  271,  244,  232,  226,  215,  205,  200,  155,
      130,  123, 1038,   78, 1038, 1038,  719,  732,  745,  758,
      771,  784,  797,  810,  823,  836,  839,  847,  855,  867,
      870,  882,  895,  904,  913,  926,  939,  952,  964,  977,
      990, 1003, 1008, 1020,    0, 1025
    } ;

static yyconst short int yy_def[277] =
    {   0,
      247,  247,  246,    3,  246,    5,  248,  248,  249,  249,
      247,   11,  250,  250,  251,  251,  252,  252,  253,  253,
      254,  254,  247,  247,  255,  255,  246,  246,  246,  246,
      246,  246,  246,  246,  256,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  257,  257,  246,
      246,  246,  246,  246,  246,  246,  258,  246,  258,   59,
      246,  246,   59,  246,   59,   45,  246,  259,  259,   69,
      260,  246,  260,  260,  260,  260,  246,  246,  246,  246,
      246,  261,  262,  246,  263,  263,  264,   86,  265,  246,
      266,  246,  267,  246,  246,  246,  268,  246,  269,  270,

      246,  256,  256,  246,  256,  246,   45,  246,  271,  246,
      246,  246,  246,  257,  257,  258,  258,  246,  117,  246,
      117,  246,  272,  270,  272,  258,  273,  246,  246,   69,
      246,  246,  260,  274,  261,  262,  246,  246,  263,   86,
      264,  264,  264,  265,  266,  267,  246,  246,  246,  268,
      246,  246,  246,  246,  270,  270,  156,  256,  246,  246,
      246,  246,  271,  246,  246,  246,  246,  246,  257,  246,
      246,  246,  246,  272,  246,  125,  125,  272,  124,  124,
      124,  246,  275,  273,  246,  274,  274,  187,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  270,  156,

      246,  246,  246,  246,  246,  257,  272,  124,  270,  276,
      274,  187,  270,  270,  246,  246,  246,  257,  276,  274,
      274,  246,  246,  246,  257,  246,  246,  257,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,    0,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246
    } ;

static yyconst short int yy_nxt[1081] =
    {   0,
      246,   95,   95,   95,  246,   29,   29,  101,  101,  101,
      246,  210,  102,  246,  246,   96,  246,   30,   30,   31,
       32,   33,   32,   31,   34,   35,   31,   36,   31,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   31,   46,
       31,   47,   31,   48,   48,   48,   48,   49,   48,   48,
       48,   48,   48,   48,   48,   48,   50,   31,   51,   52,
       53,   54,   55,   56,   55,   57,   58,   57,   59,   60,
       61,   62,   62,   60,   60,   62,   63,   64,   65,   66,
       67,   62,   60,   60,   60,   68,   69,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   70,   62,   54,

       62,   54,   54,   72,   72,   73,  245,   74,   72,   72,
       73,   98,   74,   78,   78,   78,   98,   29,  106,   75,
      107,  100,   76,  104,   75,  121,  109,   76,  246,   79,
      104,  141,   80,   78,   78,   78,  143,   29,  123,  106,
       99,  107,   95,   95,   95,   99,  101,  101,  101,   79,
      244,  102,   80,   81,   81,   81,   96,   29,  243,  105,
      118,  118,  118,  104,  233,  124,  105,  234,  121,   30,
      125,  246,  117,  170,  122,  170,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   86,
      242,   86,   86,   86,  137,  138,  137,   87,   86,  105,

       86,  171,   88,  172,   86,  141,   86,   86,   86,   86,
      143,   86,   86,   86,  147,  148,  147,   87,   86,  171,
       86,  171,   88,  173,   86,  173,   86,   86,   86,  110,
      110,  110,  241,  118,  118,  118,  240,  118,  118,  118,
      149,  149,  149,  111,  112,  239,  107,  119,  182,  183,
      120,  122,  238,  207,  108,  207,  113,  118,  118,  118,
      116,  237,  116,  116,  116,  101,  101,  101,  116,  116,
      102,  121,  209,  116,  209,  126,  236,  116,  116,  116,
      127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
      127,  127,  127,  128,  128,  128,  128,  128,  128,  235,

      151,  152,  151,  231,  131,  182,  183,  129,  153,  230,
      129,  140,  155,  140,  140,  140,  158,  159,  158,  141,
      140,  229,  140,  211,  140,  228,  140,  199,  140,  140,
      140,  156,  213,  156,  156,  156,  167,  227,  167,  157,
      156,  168,  156,  225,  156,  199,  156,  175,  156,  156,
      156,  182,  183,  105,  160,  160,  160,  205,  110,  110,
      110,  165,  212,  165,  165,  204,  165,  204,  161,  155,
      205,  108,  111,  160,  160,  160,  165,  118,  118,  118,
      211,  162,  128,  128,  128,  220,  183,  161,  182,  183,
      166,  122,  137,  138,  137,  208,  129,  192,  192,  192,

      162,  175,  175,  176,  175,  176,  176,  176,  141,  120,
      206,  176,  176,  168,  177,  178,  176,  178,  176,  164,
      176,  176,  176,  179,  200,  179,  179,  179,  147,  148,
      147,  180,  179,  199,  181,  141,  179,  246,  179,  117,
      179,  179,  179,  175,  120,  176,  117,  176,  176,  176,
      149,  149,  149,  176,  176,  169,  177,  164,  176,  108,
      176,  104,  176,  176,  176,  185,  100,  185,  185,  134,
      185,  189,  190,  189,  193,  194,  193,  132,  117,  191,
      185,  155,  195,  115,  187,  108,  187,  187,  187,  151,
      152,  151,  188,  187,  100,  187,  246,  187,   94,  187,

       94,  187,  187,  187,  196,  197,  196,  158,  159,  158,
       92,   92,  198,  156,   90,  156,  156,  156,  201,  159,
      201,  157,  156,   90,  156,   84,  156,   84,  156,  246,
      156,  156,  156,  160,  160,  160,  203,  246,  203,  203,
      246,  203,  246,  246,  105,  246,  246,  161,  160,  160,
      160,  203,  160,  160,  160,  202,  189,  190,  189,  189,
      190,  189,  161,  246,  191,  166,  161,  191,  246,  168,
      192,  192,  192,  246,  246,  162,  155,  246,  246,  187,
      246,  187,  187,  187,  214,  215,  214,  188,  187,  246,
      187,  246,  187,  246,  187,  246,  187,  187,  187,  193,

      194,  193,  193,  194,  193,  246,  246,  195,  246,  246,
      195,  196,  197,  196,  196,  197,  196,  246,  246,  198,
      246,  246,  198,  201,  216,  201,  201,  216,  201,  160,
      160,  160,  217,  217,  217,  214,  215,  214,  214,  215,
      221,  246,  246,  161,  246,  246,  205,  214,  215,  214,
      214,  215,  214,  222,  215,  222,  246,  246,  199,  246,
      246,  199,  201,  159,  201,  218,  246,  223,  223,  223,
      214,  215,  221,  214,  215,  221,  222,  215,  222,  246,
      246,  211,  246,  246,  211,  223,  223,  223,  232,  232,
      232,  246,  246,  246,  246,  246,  246,  246,  246,  202,

      224,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  226,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       93,   93,   93,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,  103,  103,  103,  103,
      103,  103,  103,  103,  103,  103,  103,  103,  103,  114,
      114,  116,  246,  246,  116,  116,  130,  130,  130,  246,
      246,  246,  246,  130,  246,  130,  130,  133,  246,  246,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      135,  135,  136,  136,  136,  136,  136,  136,  246,  136,
      136,  136,  136,  136,  136,  139,  139,  139,  139,  139,

      139,  139,  246,  139,  139,  139,  139,  139,  142,  246,
      246,  142,  142,  144,  144,  144,  144,  144,  246,  144,
      144,  144,  144,  144,  144,  144,  145,  145,  145,  145,
      145,  246,  145,  145,  145,  145,  145,  145,  145,  146,
      146,  146,  146,  146,  146,  246,  146,  146,  146,  146,
      146,  146,  150,  150,  150,  150,  150,  150,  246,  150,
      150,  150,  150,  150,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  155,  155,  246,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  155,
      163,  163,  163,  163,  163,  163,  163,  163,  163,  163,

      163,  163,  163,  174,  174,  174,  174,  174,  174,  174,
      174,  174,  174,  174,  174,  174,  184,  184,  184,  184,
      186,  186,  246,  186,  186,  186,  186,  186,  186,  186,
      186,  186,  186,  219,  219,  219,  219,   27,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246
    } ;

static yyconst short int yy_chk[1081] =
    {   0,
        0,   23,   23,   23,    0,    1,    2,   32,   32,   32,
        0,  275,   32,    0,    0,   23,    0,    1,    2,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    7,    7,    7,  244,    7,    8,    8,
        8,   25,    8,    9,    9,    9,   26,    9,   42,    7,
       42,   44,    7,   35,    8,   60,   44,    8,   60,    9,
      102,   87,    9,   10,   10,   10,   87,   10,   63,   63,
       25,   63,   24,   24,   24,   26,   33,   33,   33,   10,
      242,   33,   10,   11,   11,   11,   24,   11,  241,   35,
       62,   62,   62,  103,  232,   65,  102,  232,   65,   11,
       65,   65,  117,  117,   62,  117,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   15,
      240,   15,   15,   15,   84,   84,   84,   15,   15,  103,

       15,  119,   15,  119,   15,  141,   15,   15,   15,   16,
      141,   16,   16,   16,   94,   94,   94,   16,   16,  121,
       16,  121,   16,  122,   16,  122,   16,   16,   16,   45,
       45,   45,  239,   59,   59,   59,  238,   64,   64,   64,
       95,   95,   95,   45,   45,  237,   45,   59,  127,  127,
       59,   64,  236,  177,   64,  177,   45,   67,   67,   67,
       67,  235,   67,   67,   67,  101,  101,  101,   67,   67,
      101,   67,  181,   67,  181,   67,  234,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   68,   68,   68,   69,   69,   69,  233,

       98,   98,   98,  229,   69,  184,  184,   68,   98,  227,
       69,   86,  186,   86,   86,   86,  105,  105,  105,   86,
       86,  226,   86,  186,   86,  225,   86,  199,   86,   86,
       86,  100,  199,  100,  100,  100,  113,  224,  113,  100,
      100,  113,  100,  218,  100,  209,  100,  207,  100,  100,
      100,  210,  210,  105,  108,  108,  108,  204,  110,  110,
      110,  111,  188,  111,  111,  162,  111,  162,  108,  211,
      162,  108,  110,  112,  112,  112,  111,  118,  118,  118,
      211,  108,  128,  128,  128,  211,  182,  112,  219,  219,
      112,  118,  137,  137,  137,  180,  128,  143,  143,  143,

      112,  123,  178,  123,  174,  123,  123,  123,  143,  172,
      169,  123,  123,  167,  123,  123,  123,  123,  123,  163,
      123,  123,  123,  124,  157,  124,  124,  124,  147,  147,
      147,  124,  124,  155,  124,  142,  124,  130,  124,  126,
      124,  124,  124,  125,  120,  125,  116,  125,  125,  125,
      149,  149,  149,  125,  125,  115,  125,  109,  125,  106,
      125,  104,  125,  125,  125,  129,   79,  129,  129,   75,
      129,  138,  138,  138,  148,  148,  148,   70,   57,  138,
      129,  134,  148,   49,  134,   43,  134,  134,  134,  151,
      151,  151,  134,  134,   30,  134,   27,  134,   22,  134,

       21,  134,  134,  134,  152,  152,  152,  158,  158,  158,
       20,   19,  152,  156,   18,  156,  156,  156,  159,  159,
      159,  156,  156,   17,  156,   14,  156,   13,  156,    0,
      156,  156,  156,  160,  160,  160,  161,    0,  161,  161,
        0,  161,    0,    0,  158,    0,    0,  160,  166,  166,
      166,  161,  168,  168,  168,  159,  189,  189,  189,  190,
      190,  190,  166,    0,  189,  166,  168,  190,    0,  168,
      192,  192,  192,    0,    0,  166,  187,    0,    0,  187,
        0,  187,  187,  187,  200,  200,  200,  187,  187,    0,
      187,    0,  187,    0,  187,    0,  187,  187,  187,  193,

      193,  193,  194,  194,  194,    0,    0,  193,    0,    0,
      194,  196,  196,  196,  197,  197,  197,    0,    0,  196,
        0,    0,  197,  201,  201,  201,  202,  202,  202,  205,
      205,  205,  206,  206,  206,  208,  208,  208,  212,  212,
      212,    0,    0,  205,    0,    0,  205,  213,  213,  213,
      214,  214,  214,  215,  215,  215,    0,    0,  213,    0,
        0,  214,  216,  216,  216,  206,    0,  217,  217,  217,
      220,  220,  220,  221,  221,  221,  222,  222,  222,    0,
        0,  220,    0,    0,  221,  223,  223,  223,  230,  230,
      230,    0,    0,    0,    0,    0,    0,    0,    0,  216,

      217,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  223,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  249,  249,  249,  249,  249,
      249,  249,  249,  249,  249,  249,  249,  249,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  251,  251,  251,  251,  251,  251,  251,  251,  251,
      251,  251,  251,  251,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  253,  253,  253,

      253,  253,  253,  253,  253,  253,  253,  253,  253,  253,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  255,  255,  255,  256,  256,  256,  256,
      256,  256,  256,  256,  256,  256,  256,  256,  256,  257,
      257,  258,    0,    0,  258,  258,  259,  259,  259,    0,
        0,    0,    0,  259,    0,  259,  259,  260,    0,    0,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      261,  261,  262,  262,  262,  262,  262,  262,    0,  262,
      262,  262,  262,  262,  262,  263,  263,  263,  263,  263,

      263,  263,    0,  263,  263,  263,  263,  263,  264,    0,
        0,  264,  264,  265,  265,  265,  265,  265,    0,  265,
      265,  265,  265,  265,  265,  265,  266,  266,  266,  266,
      266,    0,  266,  266,  266,  266,  266,  266,  266,  267,
      267,  267,  267,  267,  267,    0,  267,  267,  267,  267,
      267,  267,  268,  268,  268,  268,  268,  268,    0,  268,
      268,  268,  268,  268,  269,  269,  269,  269,  269,  269,
      269,  269,  269,  269,  269,  269,  269,  270,  270,    0,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  273,  273,  273,  273,
      274,  274,    0,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  276,  276,  276,  276,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  246
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pgc.l"
#define INITIAL 0
/* This is a modified version of src/backend/parser/scan.l */
#line 3 "pgc.l"
#include "config.h"

#include <ctype.h>
#include <sys/types.h>
#include <limits.h>

#ifndef PATH_MAX
#include <sys/param.h>
#define PATH_MAX MAXPATHLEN
#endif

#if defined(HAVE_STRING_H)
#include <string.h>
#else
#include <strings.h>
#endif
#include <errno.h>

#include "postgres.h"
#include "miscadmin.h"
#include "nodes/pg_list.h"
#include "nodes/parsenodes.h"
#include "parser/gramparse.h"
#include "parser/scansup.h"
#include "extern.h"
#include "preproc.h"
#include "utils/builtins.h"

#ifdef  YY_READ_BUF_SIZE
#undef  YY_READ_BUF_SIZE
#endif
#define YY_READ_BUF_SIZE	MAX_PARSE_BUFFER

/* some versions of lex define this as a macro */
#if defined(yywrap)
#undef yywrap
#endif /* yywrap */

extern YYSTYPE yylval;
int llen;
char literal[MAX_PARSE_BUFFER];
int before_comment;

struct _yy_buffer { YY_BUFFER_STATE 	buffer;
		    long		lineno;
		    char	      * filename;
		    struct _yy_buffer * next;
		  } *yy_buffer = NULL;

struct _defines *defines = NULL;
static char *old;

#define C 1
#define SQL 2
#define incl 3
#define def 4
#define def_ident 5

/* OK, here is a short description of lex/flex rules behavior.
 * The longest pattern which matches an input string is always chosen.
 * For equal-length patterns, the first occurring in the rules list is chosen.
 * INITIAL is the starting condition, to which all non-conditional rules apply.
 * When in an exclusive condition, only those rules defined for that condition apply.
 *
 * Exclusive states change parsing rules while the state is active.
 * There are exclusive states for quoted strings, extended comments,
 *  and to eliminate parsing troubles for numeric strings.
 * Exclusive states:
 *  <xb> binary numeric string - thomas 1997-11-16
 *  <xc> extended C-style comments - tgl 1997-07-12
 *  <xd> delimited identifiers (double-quoted identifiers) - tgl 1997-10-27
 *  <xh> hexadecimal numeric string - thomas 1997-11-16
 *  <xm> numeric strings with embedded minus sign - tgl 1997-09-05
 *  <xq> quoted strings - tgl 1997-07-30
 *
 * The "extended comment" syntax closely resembles allowable operator syntax.
 * So, when in condition <xc>, only strings which would terminate the
 *  "extended comment" trigger any action other than "ignore".
 * Be sure to match _any_ candidate comment, including those with appended
 *	operator-like symbols. - thomas 1997-07-14
 */
#define xb 6

#define xc 7

#define xd 8

#define xdc 9

#define xh 10

#define xm 11

#define xq 12

/* Binary number
 */
/* Hexadecimal number
 */
/* Extended quote
 * xqdouble implements SQL92 embedded quote
 * xqcat allows strings to cross input lines
 */
/* Delimited quote
 * Allows embedded spaces and other special characters into identifiers.
 */
/* Comments
 * Ignored by the scanner and parser.
 */
/*
real			[\-]?{digit}+\.{digit}+([Ee][-+]?{digit}+)?
*/
/* some stuff needed for ecpg */
/* DO NOT PUT ANY COMMENTS IN THE FOLLOWING SECTION.
 * AT&T lex does not properly handle C-style comments in this second lex block.
 * So, put comments here. tgl - 1997-09-08
 *
 * Quoted strings must allow some special characters such as single-quote
 *  and newline.
 * Embedded single-quotes are implemented both in the SQL/92-standard
 *  style of two adjacent single quotes "''" and in the Postgres/Java style
 *  of escaped-quote "\'".
 * Other embedded escaped characters are matched explicitly and the leading
 *  backslash is dropped from the string. - thomas 1997-09-24
 */
#line 867 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 183 "pgc.l"

#line 1020 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 247 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1038 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 184 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 186 "pgc.l"
{ ECHO; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 188 "pgc.l"
{ ECHO; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 189 "pgc.l"
{
				before_comment = YYSTATE;
				ECHO;
	 			BEGIN(xc);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 195 "pgc.l"
{ ECHO; BEGIN(before_comment); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 197 "pgc.l"
{ ECHO; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 199 "pgc.l"
{
					BEGIN(xb);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 204 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,2);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad binary integer input!");
					return ICONST;
				}
	YY_BREAK
case 9:
#line 215 "pgc.l"
case 10:
YY_RULE_SETUP
#line 215 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 11:
#line 222 "pgc.l"
case 12:
YY_RULE_SETUP
#line 222 "pgc.l"
{
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 225 "pgc.l"
{
					BEGIN(xh);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 230 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,16);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad hexadecimal integer input");
					return ICONST;
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 241 "pgc.l"
{
					BEGIN(xq);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 246 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(scanstr(literal));
					return SCONST;
				}
	YY_BREAK
case 17:
#line 252 "pgc.l"
case 18:
#line 253 "pgc.l"
case 19:
YY_RULE_SETUP
#line 253 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 259 "pgc.l"
{
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 263 "pgc.l"
{
					BEGIN(xd);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 268 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 273 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 279 "pgc.l"
{
					BEGIN(xdc);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 284 "pgc.l"
{
					BEGIN(C);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 289 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 296 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 297 "pgc.l"
{
					BEGIN(SQL);
					return yytext[0];
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 303 "pgc.l"
{ 	return TYPECAST; }
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 304 "pgc.l"
{
					BEGIN(xm);
					return yytext[0];
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 308 "pgc.l"
{ /* 
				   * We may find a ';' inside a structure
				   * definition in a TYPE or VAR statement.
				   * This is not an EOL marker.
				   */
				  if (yytext[0] == ';' && struct_level == 0)
					 BEGIN C;
				  return yytext[0];
				}
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 317 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 321 "pgc.l"
{
					if (strcmp((char*)yytext,"!=") == 0)
						yylval.str = mm_strdup("<>"); /* compatability */
					else
						yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 328 "pgc.l"
{
					yylval.ival = atoi((char*)&yytext[1]);
					return PARAM;
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 332 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					BEGIN(xm);
					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 385 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 402 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.dval = strtod(((char *)yytext),&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float8 input");
					return FCONST;
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 412 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 428 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.dval = strtod((char *)yytext,&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float input");
					return FCONST;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 437 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext+1);
					return(CVARIABLE);
			}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 441 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 493 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 494 "pgc.l"
{ return yytext[0]; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 495 "pgc.l"
{ BEGIN SQL; return SQL_START; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 496 "pgc.l"
{ /* ignore */ } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 497 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return(CPP_LINE);
				}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 501 "pgc.l"
{
					ScanKeyword		*keyword;

					keyword = ScanCKeywordLookup((char*)yytext);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						struct _defines *ptr;

						for (ptr = defines; ptr; ptr = ptr->next)
						{
							if (strcmp(yytext, ptr->old) == 0)
							{
								struct _yy_buffer *yb;

								yb = mm_alloc(sizeof(struct _yy_buffer));

					                        yb->buffer =  YY_CURRENT_BUFFER;
					                        yb->lineno = yylineno;
					                        yb->filename = mm_strdup(input_filename);
					                        yb->next = yy_buffer;

					                        yy_buffer = yb;

								yy_scan_string(ptr->new);
								break;
							}
						}
						if (ptr == NULL) 
						{
							yylval.str = mm_strdup((char*)yytext);
							return IDENT;
						}
					}
				}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 538 "pgc.l"
{ return(';'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 539 "pgc.l"
{ return(','); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 540 "pgc.l"
{ return('*'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 541 "pgc.l"
{ return('%'); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 542 "pgc.l"
{ return('/'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 543 "pgc.l"
{ return('+'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 544 "pgc.l"
{ return('-'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 545 "pgc.l"
{ return('('); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 546 "pgc.l"
{ return(')'); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 547 "pgc.l"
{ ECHO; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 548 "pgc.l"
{ return('{'); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 549 "pgc.l"
{ return('}'); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 550 "pgc.l"
{ return('['); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 551 "pgc.l"
{ return(']'); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 552 "pgc.l"
{ return('='); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 553 "pgc.l"
{ return S_ANYTHING; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 554 "pgc.l"
{BEGIN(def_ident);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 555 "pgc.l"
{}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 556 "pgc.l"
{
				old = mm_strdup(yytext);
				BEGIN(def);
				llen = 0;
				*literal = '\0';
			}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 562 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 563 "pgc.l"
{
				struct _defines *ptr, *this;
        
                                for (ptr = defines; ptr != NULL; ptr = ptr->next)
                                {
                                     if (strcmp(old, ptr->old) == 0)
                                     {
					free(ptr->new);
					ptr->new = mm_strdup(scanstr(literal));
                                     }
                                }
				if (ptr == NULL)
				{                        
                                        this = (struct _defines *) mm_alloc(sizeof(struct _defines));

                                        /* initial definition */
                                        this->old = old;
                                        this->new = mm_strdup(scanstr(literal));
					this->next = defines;
					defines = this;
				}

				BEGIN(C);
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 587 "pgc.l"
{
				if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
					yyerror("ERROR: define statement parse buffer exceeded");
				memcpy(literal+llen, yytext, yyleng+1);
				llen += yyleng;
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 593 "pgc.l"
{ BEGIN(incl); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 594 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 595 "pgc.l"
{ /* got the include file name */
			  struct _yy_buffer *yb;
			  struct _include_path *ip;
			  char inc_file[PATH_MAX];

			  yb = mm_alloc(sizeof(struct _yy_buffer));

			  yb->buffer =  YY_CURRENT_BUFFER;
			  yb->lineno = yylineno;
			  yb->filename = input_filename;
			  yb->next = yy_buffer;

			  yy_buffer = yb;

			  if (yytext[strlen(yytext) - 1] == ';')
				yytext[strlen(yytext) - 1] = '\0';

			  yyin = NULL;
			  for (ip = include_paths; yyin == NULL && ip != NULL; ip = ip->next)
			  {
				if (strlen(ip->path) + strlen(yytext) + 3 > PATH_MAX)
				{
					fprintf(stderr, "Error: Path %s/%s is too long in line %d, skipping.\n", ip->path, yytext, yylineno);
					continue;
				}
			  	sprintf (inc_file, "%s/%s", ip->path, yytext);
		          	yyin = fopen( inc_file, "r" );
			  	if (!yyin)
				{
					if (strcmp(inc_file + strlen(inc_file) - 2, ".h"))
					{
						strcat(inc_file, ".h");
						yyin = fopen( inc_file, "r" );
					}

				}
			  }
			  if (!yyin)
			  {
				fprintf(stderr, "Error: Cannot open include file %s in line %d\n", yytext, yylineno);
				exit(NO_INCLUDE_FILE); 
			  }

			  input_filename = mm_strdup(inc_file);
			  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE ));
			  yylineno = 0;
			  output_line_number();

			  BEGIN C;
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 645 "pgc.l"
{ BEGIN C; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C):
case YY_STATE_EOF(SQL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(def):
case YY_STATE_EOF(def_ident):
case YY_STATE_EOF(xb):
case YY_STATE_EOF(xc):
case YY_STATE_EOF(xd):
case YY_STATE_EOF(xdc):
case YY_STATE_EOF(xh):
case YY_STATE_EOF(xm):
case YY_STATE_EOF(xq):
#line 646 "pgc.l"
{ if (yy_buffer == NULL)
				yyterminate();
			  else
			  {
				struct _yy_buffer *yb = yy_buffer;

				if (yyin != NULL)
					fclose(yyin);

				yy_delete_buffer( YY_CURRENT_BUFFER );
				yy_switch_to_buffer(yy_buffer->buffer);

				yylineno = yy_buffer->lineno;

				free(input_filename);
				input_filename = yy_buffer->filename;

				yy_buffer = yy_buffer->next;
				free(yb);
				output_line_number();
			  }
			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 668 "pgc.l"
ECHO;
	YY_BREAK
#line 1912 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 247 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 247 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 246);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 668 "pgc.l"

void
lex_init(void)
{
    braces_open = 0;
    BEGIN C;
}

int yywrap(void) 
{ 
    return 1;
}
