/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
static yyconst short int yy_acclist[309] =
    {   0,
       10,   10,    6,    6,   23,   23,   26,   26,    9,    9,
       27,   27,   18,   18,   71,   70,   24,   70,   70,   59,
       70,   53,   59,   70,   53,   70,   24,   59,   70,   48,
       59,   70,   52,   59,   70,   51,   59,   70,   59,   70,
       59,   70,   41,   59,   70,16424,   50,   59,   70,   58,
       59,   70,   49,   59,   70,   49,   59,   70,   56,   59,
       70,   57,   59,   70,   54,   59,   70,   55,   59,   70,
       45,   70,   44,   45,   70,   44,   70,   33,   45,   70,
       21,   24,   45,   70,   31,   33,   45,   70,   31,   33,
       45,   70,   15,   45,   70,   31,   45,   70,   31,   33,

       45,   70,   31,   45,   70,   31,   33,   45,   70,   38,
       45,   70,16420,   31,   33,   45,   70,   43,   45,   70,
    16419,   43,   45,   70,16419,   43,   45,   70,16419,   68,
       70,   67,   70,   67,   68,   70,   24,   68,   70,   68,
       70,   68,   69,   70,   65,   70,   63,   65,   70,   65,
       70,   64,   70,   61,   70,   62,   70,   10,   70,    8,
       70,    3,    6,   70,    3,    6,   70,    3,   70,    6,
       70,   23,   70,   22,   70,   26,   70,   25,   70,    9,
       70,   14,   70,   27,   70,   28,   70,   18,   70,   16,
       70,   70,    4,   48,   48,   48,   48,   41,16424,   49,

       49,   33,   33,   33,   34,   33,   33,   38,16420,   39,
    16421,    4,   33,   33,   39,16421,   29,   33,   42,   43,
    16419,    7,   13,   68,    4,   68,   62,   10,    6,    6,
        5,   23,   26,    9,   27,   18,   17,   19,    4,    4,
       48,   48,   47, 8232,   49,   32,   30,   32,   30,   32,
       34,   30,    1,   33,   33,   30,   32,    4,   33,    4,
       33,    4,   33, 8228,   39,16421,   39,16421,   42, 8227,
       68,    4,   68,    4,   68,   12,    5,   11,   20,    2,
        4,   49,   32, 8229,   39,16421,    2,    4,   33,   32,
       42,   68,    2,    4,   68,    2,    2,    2,   48,   42,

        2,   68,    2,   68,    2,   46,   60,   66
    } ;

static yyconst short int yy_accept[240] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    2,    3,    4,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   19,
       20,   22,   25,   27,   30,   33,   36,   39,   41,   43,
       47,   50,   53,   56,   59,   62,   65,   68,   71,   73,
       76,   78,   81,   85,   89,   93,   96,   99,  103,  106,
      110,  114,  118,  122,  126,  130,  132,  134,  137,  140,
      142,  145,  147,  150,  152,  154,  156,  158,  160,  162,
      165,  168,  170,  172,  174,  176,  178,  180,  182,  184,
      186,  188,  190,  192,  193,  194,  194,  195,  196,  197,

      198,  200,  200,  200,  200,  201,  202,  203,  204,  204,
      205,  206,  207,  207,  208,  208,  210,  212,  214,  215,
      215,  215,  217,  217,  219,  220,  220,  220,  222,  223,
      224,  225,  227,  228,  229,  229,  229,  230,  231,  231,
      231,  232,  233,  234,  235,  235,  235,  236,  237,  237,
      237,  238,  239,  239,  240,  241,  242,  243,  243,  244,
      245,  246,  247,  249,  252,  253,  253,  254,  255,  256,
      258,  258,  258,  258,  260,  262,  264,  265,  267,  267,
      269,  269,  269,  270,  271,  272,  274,  276,  276,  276,
      277,  278,  278,  278,  279,  279,  279,  280,  280,  282,

      282,  282,  283,  284,  285,  285,  287,  290,  291,  292,
      293,  296,  297,  298,  299,  300,  300,  301,  303,  305,
      306,  306,  306,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  308,  308,  309,  309
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    5,   10,   11,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,    9,
       21,   22,    5,    5,   23,   24,   25,   26,   27,   28,
       23,   23,   29,   23,   23,   30,   23,   31,   23,   23,
       32,   23,   33,   23,   34,   23,   23,   35,   23,   23,
       36,   37,   38,    5,   23,    1,   23,   24,   25,   26,

       27,   28,   23,   23,   29,   23,   23,   30,   23,   31,
       23,   23,   32,   23,   33,   23,   34,   23,   23,   35,
       23,   23,   39,    9,   40,    5,    1,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,

       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    2,    3,    4,    5,    6,    5,    5,    5,    7,
        1,    8,    5,    1,    9,   10,    5,   11,    5,    1,
        5,    5,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,    1,   13,    1,    1,    1
    } ;

static yyconst short int yy_base[269] =
    {   0,
        0,    1,   18,    0,   58,    0,   97,  102,  107,  126,
      145,    0,  444,  440,  176,  194,  442,  440,  438,  435,
      430,  426,    0,  135,   97,  105,  434, 1024, 1024,  418,
     1024,    6,  150, 1024,   99, 1024, 1024,  410,  104,  215,
     1024, 1024,    0,  391, 1024, 1024, 1024, 1024, 1024, 1024,
     1024,  409, 1024,  219,  105, 1024,  223,  140,  237,  148,
      254,  280,  244,  258,  411,    0, 1024,    0,    0,  408,
        0, 1024, 1024,  404, 1024, 1024,    0,    0,  240,    0,
      311,  114,    0,    0, 1024,    0, 1024,    0,  247,  261,
     1024,    0,  276,    0,  329,  350,  122,  130,  408,  356,

      359,  398,  363,  355,    0,  368,  373,  213,  377,  174,
      369,  178,  192,  391,  365,    0,  387,  410,  430,  382,
      440,  358,  444,  360,  125,  461,  453,  362, 1024, 1024,
        0,  479,    0,    0,  272,  475,    0,    0,  170,  357,
      470,    0,    0,    0,  500,  503,  506,    0,  512,  515,
     1024, 1024,  352,  521,  339,  518,  542,  352, 1024, 1024,
      324, 1024, 1024,  329, 1024,  342, 1024,    0,  196,  340,
      545,  538,  544,    0,  322,  278, 1024,  313,  311,  565,
      305,    0,  129, 1024,  233,  582,  305,  568,  571, 1024,
      603,  606,  609, 1024,  618,  621, 1024,  188,  630,  633,

      636,  639,  318, 1024,  299,  642,  645,  288,  238,  323,
      648,  651,  662,  665,  668,  265,  251,  673,  676,  679,
      259,  260,  687,  135,  250,  240,  208,  207,  195,  190,
      173,  152,  108,   92, 1024,   85, 1024, 1024,  705,  718,
      731,  744,  757,  770,  783,  796,  809,  822,  825,  833,
      841,  853,  856,  868,  881,  890,  899,  912,  925,  938,
      950,  963,  976,  989,  994, 1006,    0, 1011
    } ;

static yyconst short int yy_def[269] =
    {   0,
      239,  239,  238,    3,  238,    5,  240,  240,  241,  241,
      239,   11,  242,  242,  243,  243,  244,  244,  245,  245,
      246,  246,  239,  239,  247,  247,  238,  238,  238,  238,
      238,  238,  238,  238,  248,  238,  238,  238,  238,  238,
      238,  238,  249,  249,  238,  238,  238,  238,  238,  238,
      238,  250,  238,  250,   54,  238,  238,   54,  238,   54,
      238,  238,  251,  251,   64,  252,  238,  252,  252,  252,
      252,  238,  238,  238,  238,  238,  253,  254,  238,  255,
      255,  256,   81,  257,  238,  258,  238,  259,  238,  238,
      238,  260,  238,  261,  262,  238,  248,  248,  238,  248,

      238,  263,  238,  238,  249,  249,  250,  250,  238,  108,
      238,  108,  238,  264,  238,   61,  238,  262,  264,  238,
      238,  117,  238,  250,  265,  238,  238,   64,  238,  238,
      252,  266,  253,  254,  238,  238,  255,   81,  256,  256,
      256,  257,  258,  259,  238,  238,  238,  260,  238,  238,
      238,  238,  262,  262,  154,  248,  238,  263,  238,  238,
      249,  238,  238,  238,  238,  264,  238,  119,  119,  264,
      238,  238,  238,  118,  118,  118,  238,  117,  238,  238,
      238,  267,  265,  238,  266,  266,  186,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  262,  154,  238,

      238,  249,  264,  238,  238,  238,  118,  262,  268,  266,
      186,  262,  262,  238,  238,  238,  268,  266,  266,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,    0,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238
    } ;

static yyconst short int yy_nxt[1065] =
    {   0,
      238,   90,   90,   90,  238,   29,   29,   96,   96,   96,
      238,  209,   97,  238,   91,  238,   30,   30,   31,   32,
       33,   32,   31,   34,   35,   31,   31,   31,   31,   36,
       31,   37,   38,   31,   39,   40,   31,   41,   42,   31,
       43,   43,   43,   43,   44,   43,   43,   43,   43,   43,
       43,   43,   43,   45,   31,   46,   47,   48,   49,   50,
       51,   50,   52,   53,   52,   54,   55,   56,   57,   55,
       55,   57,   58,   59,   60,   61,   62,   57,   55,   55,
       63,   64,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   65,   57,   49,   57,   49,   49,   67,   67,

       68,   99,   69,   67,   67,   68,   93,   69,   73,   73,
       73,  237,   29,   70,   93,   95,   71,  236,   70,  112,
      102,   71,  238,   74,   99,  139,   75,   73,   73,   73,
      141,   29,   99,   94,  235,  100,   90,   90,   90,  181,
      182,   94,   74,  181,  182,   75,   76,   76,   76,   91,
       29,   96,   96,   96,  114,  115,   97,  116,  100,  118,
      225,   30,  112,  226,  119,  238,  100,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,   77,
       81,  139,   81,   81,   81,  234,  141,   82,   81,  163,
       81,  164,   83,  163,   81,  163,   81,   81,   81,  198,

       81,   81,   81,  233,  212,   82,   81,  165,   81,  165,
       83,  203,   81,  203,   81,   81,  103,  103,  103,  232,
      109,  109,  109,  231,  109,  109,  109,  108,  162,  104,
      162,  230,  101,  110,  153,  229,  111,  113,  109,  109,
      109,  135,  136,  135,  210,  126,  126,  126,  145,  146,
      145,  113,  181,  182,  117,  120,  120,  120,  127,  126,
      126,  126,  147,  147,  147,  181,  182,  129,  121,  122,
      228,  116,  127,  135,  136,  135,  227,  149,  150,  149,
      123,  109,  109,  109,  107,  151,  107,  107,  107,  223,
      222,  107,  107,  208,  112,  208,  107,  221,  124,  198,

      107,  107,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  125,  125,  138,  206,  138,  138,  138,
      167,  211,  139,  138,  153,  138,  182,  138,  180,  138,
      178,  138,  138,  154,  210,  154,  154,  154,  207,  218,
      155,  154,  167,  154,  167,  154,  111,  154,  202,  154,
      154,   96,   96,   96,  159,  199,   97,  156,  157,  156,
      103,  103,  103,  198,  103,  103,  103,  160,  139,  160,
      160,  238,  160,  104,  108,  178,  101,  104,  109,  109,
      109,  160,  117,  120,  120,  120,  111,  108,  171,  171,
      171,  113,  100,  167,  161,  168,  121,  168,  168,  168,

      159,  172,  168,  168,  117,  169,  170,  168,  170,  168,
       99,  168,  168,  173,  174,   95,  174,  174,  174,  132,
      130,  175,  174,  108,  176,  106,  174,  101,  174,   95,
      174,  174,  167,  238,  168,   89,  168,  168,  168,   89,
       87,  168,  168,   87,  169,   85,  168,   85,  168,   79,
      168,  168,  177,   79,  177,  177,  179,  177,  179,  238,
      238,  180,  126,  126,  126,  184,  177,  184,  184,  238,
      184,  191,  191,  191,  238,  127,  188,  189,  188,  184,
      153,  139,  238,  186,  190,  186,  186,  186,  238,  238,
      187,  186,  238,  186,  238,  186,  238,  186,  238,  186,

      186,  145,  146,  145,  192,  193,  192,  147,  147,  147,
      238,  238,  194,  149,  150,  149,  195,  196,  195,  156,
      157,  156,  238,  238,  197,  154,  238,  154,  154,  154,
      238,  238,  155,  154,  238,  154,  238,  154,  238,  154,
      238,  154,  154,  200,  157,  200,  171,  171,  171,  238,
      204,  238,  204,  204,  100,  204,  205,  238,  205,  172,
      238,  206,  238,  238,  204,  238,  171,  171,  171,  188,
      189,  188,  188,  189,  188,  238,  238,  190,  201,  172,
      190,  238,  180,  153,  238,  238,  186,  238,  186,  186,
      186,  238,  238,  187,  186,  238,  186,  238,  186,  238,

      186,  238,  186,  186,  191,  191,  191,  192,  193,  192,
      192,  193,  192,  238,  238,  194,  238,  238,  194,  195,
      196,  195,  195,  196,  195,  238,  238,  197,  238,  238,
      197,  213,  214,  213,  200,  215,  200,  200,  215,  200,
      216,  216,  216,  171,  171,  171,  213,  214,  213,  213,
      214,  219,  213,  214,  213,  238,  172,  238,  238,  206,
      238,  238,  198,  213,  214,  213,  220,  214,  220,  200,
      157,  200,  238,  198,  213,  214,  219,  213,  214,  219,
      220,  214,  220,  238,  210,  238,  238,  210,  224,  224,
      224,  238,  238,  238,  238,  238,  238,  238,  238,  238,

      238,  238,  238,  238,  201,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   80,   80,   80,   80,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   86,   86,   86,   86,   86,   86,   86,
       86,   86,   86,   86,   86,   86,   88,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   88,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   98,   98,   98,   98,   98,   98,   98,   98,
       98,   98,   98,   98,   98,  105,  105,  107,  238,  238,
      107,  107,  128,  128,  128,  238,  238,  238,  238,  128,
      238,  128,  128,  131,  238,  238,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  133,  133,  134,  134,
      134,  134,  134,  134,  238,  134,  134,  134,  134,  134,
      134,  137,  137,  137,  137,  137,  137,  137,  238,  137,
      137,  137,  137,  137,  140,  238,  238,  140,  140,  142,

      142,  142,  142,  142,  238,  142,  142,  142,  142,  142,
      142,  142,  143,  143,  143,  143,  143,  238,  143,  143,
      143,  143,  143,  143,  143,  144,  144,  144,  144,  144,
      144,  238,  144,  144,  144,  144,  144,  144,  148,  148,
      148,  148,  148,  148,  238,  148,  148,  148,  148,  148,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  153,  153,  238,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,

      166,  166,  183,  183,  183,  183,  185,  185,  238,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  217,
      217,  217,  217,   27,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238
    } ;

static yyconst short int yy_chk[1065] =
    {   0,
        0,   23,   23,   23,    0,    1,    2,   32,   32,   32,
        0,  267,   32,    0,   23,    0,    1,    2,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7,    7,

        7,   35,    7,    8,    8,    8,   25,    8,    9,    9,
        9,  236,    9,    7,   26,   39,    7,  234,    8,   55,
       39,    8,   55,    9,   97,   82,    9,   10,   10,   10,
       82,   10,   98,   25,  233,   35,   24,   24,   24,  125,
      125,   26,   10,  183,  183,   10,   11,   11,   11,   24,
       11,   33,   33,   33,   58,   58,   33,   58,   97,   60,
      224,   11,   60,  224,   60,   60,   98,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       15,  139,   15,   15,   15,  232,  139,   15,   15,  110,
       15,  110,   15,  112,   15,  112,   15,   15,   16,  198,

       16,   16,   16,  231,  198,   16,   16,  113,   16,  113,
       16,  169,   16,  169,   16,   16,   40,   40,   40,  230,
       54,   54,   54,  229,   57,   57,   57,  108,  108,   40,
      108,  228,   40,   54,  185,  227,   54,   57,   59,   59,
       59,   79,   79,   79,  185,   63,   63,   63,   89,   89,
       89,   59,  209,  209,   59,   61,   61,   61,   63,   64,
       64,   64,   90,   90,   90,  217,  217,   64,   61,   61,
      226,   61,   64,  135,  135,  135,  225,   93,   93,   93,
       61,   62,   62,   62,   62,   93,   62,   62,   62,  222,
      221,   62,   62,  176,   62,  176,   62,  216,   62,  208,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   81,  205,   81,   81,   81,
      203,  187,   81,   81,  210,   81,  181,   81,  179,   81,
      178,   81,   81,   95,  210,   95,   95,   95,  175,  210,
       95,   95,  170,   95,  166,   95,  164,   95,  161,   95,
       95,   96,   96,   96,  158,  155,   96,  100,  100,  100,
      101,  101,  101,  153,  103,  103,  103,  104,  140,  104,
      104,  128,  104,  101,  124,  122,  101,  103,  109,  109,
      109,  104,  115,  120,  120,  120,  111,  107,  117,  117,
      117,  109,  100,  114,  106,  114,  120,  114,  114,  114,

      102,  117,  114,  114,  117,  114,  114,  114,  114,  114,
       99,  114,  114,  117,  118,   74,  118,  118,  118,   70,
       65,  118,  118,   52,  118,   44,  118,   38,  118,   30,
      118,  118,  119,   27,  119,   22,  119,  119,  119,   21,
       20,  119,  119,   19,  119,   18,  119,   17,  119,   14,
      119,  119,  121,   13,  121,  121,  123,  121,  123,    0,
        0,  123,  126,  126,  126,  127,  121,  127,  127,    0,
      127,  141,  141,  141,    0,  126,  136,  136,  136,  127,
      132,  141,    0,  132,  136,  132,  132,  132,    0,    0,
      132,  132,    0,  132,    0,  132,    0,  132,    0,  132,

      132,  145,  145,  145,  146,  146,  146,  147,  147,  147,
        0,    0,  146,  149,  149,  149,  150,  150,  150,  156,
      156,  156,    0,    0,  150,  154,    0,  154,  154,  154,
        0,    0,  154,  154,    0,  154,    0,  154,    0,  154,
        0,  154,  154,  157,  157,  157,  171,  171,  171,    0,
      172,    0,  172,  172,  156,  172,  173,    0,  173,  171,
        0,  173,    0,    0,  172,    0,  180,  180,  180,  188,
      188,  188,  189,  189,  189,    0,    0,  188,  157,  180,
      189,    0,  180,  186,    0,    0,  186,    0,  186,  186,
      186,    0,    0,  186,  186,    0,  186,    0,  186,    0,

      186,    0,  186,  186,  191,  191,  191,  192,  192,  192,
      193,  193,  193,    0,    0,  192,    0,    0,  193,  195,
      195,  195,  196,  196,  196,    0,    0,  195,    0,    0,
      196,  199,  199,  199,  200,  200,  200,  201,  201,  201,
      202,  202,  202,  206,  206,  206,  207,  207,  207,  211,
      211,  211,  212,  212,  212,    0,  206,    0,    0,  206,
        0,    0,  212,  213,  213,  213,  214,  214,  214,  215,
      215,  215,    0,  213,  218,  218,  218,  219,  219,  219,
      220,  220,  220,    0,  218,    0,    0,  219,  223,  223,
      223,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  215,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  242,  242,  242,  242,  242,  242,
      242,  242,  242,  242,  242,  242,  242,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  246,  246,  246,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  247,
      247,  247,  247,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  249,  249,  250,    0,    0,
      250,  250,  251,  251,  251,    0,    0,    0,    0,  251,
        0,  251,  251,  252,    0,    0,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  253,  253,  254,  254,
      254,  254,  254,  254,    0,  254,  254,  254,  254,  254,
      254,  255,  255,  255,  255,  255,  255,  255,    0,  255,
      255,  255,  255,  255,  256,    0,    0,  256,  256,  257,

      257,  257,  257,  257,    0,  257,  257,  257,  257,  257,
      257,  257,  258,  258,  258,  258,  258,    0,  258,  258,
      258,  258,  258,  258,  258,  259,  259,  259,  259,  259,
      259,    0,  259,  259,  259,  259,  259,  259,  260,  260,
      260,  260,  260,  260,    0,  260,  260,  260,  260,  260,
      261,  261,  261,  261,  261,  261,  261,  261,  261,  261,
      261,  261,  261,  262,  262,    0,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  265,  265,  265,  265,  266,  266,    0,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  268,
      268,  268,  268,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  238,  238
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pgc.l"
#define INITIAL 0
/* This is a modified version of src/backend/parser/scan.l */
#line 3 "pgc.l"
#include "config.h"

#include <ctype.h>
#include <sys/types.h>
#include <limits.h>

#ifndef PATH_MAX
#include <sys/param.h>
#define PATH_MAX MAXPATHLEN
#endif

#if defined(HAVE_STRING_H)
#include <string.h>
#else
#include <strings.h>
#endif
#include <errno.h>

#include "postgres.h"
#include "miscadmin.h"
#include "nodes/pg_list.h"
#include "nodes/parsenodes.h"
#include "parser/gramparse.h"
#include "parser/scansup.h"
#include "extern.h"
#include "preproc.h"
#include "utils/builtins.h"

/* some versions of lex define this as a macro */
#if defined(yywrap)
#undef yywrap
#endif /* yywrap */

extern YYSTYPE yylval;
int llen;
char literal[MAX_PARSE_BUFFER];
int before_comment;

struct _yy_buffer { YY_BUFFER_STATE 	buffer;
		    long		lineno;
		    char	      * filename;
		    struct _yy_buffer * next;
		  } *yy_buffer = NULL;

struct _defines *defines = NULL;
static char *old;

#define C 1
#define SQL 2
#define incl 3
#define def 4
#define def_ident 5

/* OK, here is a short description of lex/flex rules behavior.
 * The longest pattern which matches an input string is always chosen.
 * For equal-length patterns, the first occurring in the rules list is chosen.
 * INITIAL is the starting condition, to which all non-conditional rules apply.
 * When in an exclusive condition, only those rules defined for that condition apply.
 *
 * Exclusive states change parsing rules while the state is active.
 * There are exclusive states for quoted strings, extended comments,
 *  and to eliminate parsing troubles for numeric strings.
 * Exclusive states:
 *  <xb> binary numeric string - thomas 1997-11-16
 *  <xc> extended C-style comments - tgl 1997-07-12
 *  <xd> delimited identifiers (double-quoted identifiers) - tgl 1997-10-27
 *  <xh> hexadecimal numeric string - thomas 1997-11-16
 *  <xm> numeric strings with embedded minus sign - tgl 1997-09-05
 *  <xq> quoted strings - tgl 1997-07-30
 *
 * The "extended comment" syntax closely resembles allowable operator syntax.
 * So, when in condition <xc>, only strings which would terminate the
 *  "extended comment" trigger any action other than "ignore".
 * Be sure to match _any_ candidate comment, including those with appended
 *	operator-like symbols. - thomas 1997-07-14
 */
#define xb 6

#define xc 7

#define xd 8

#define xdc 9

#define xh 10

#define xm 11

#define xq 12

/* Binary number
 */
/* Hexadecimal number
 */
/* Extended quote
 * xqdouble implements SQL92 embedded quote
 * xqcat allows strings to cross input lines
 */
/* Delimited quote
 * Allows embedded spaces and other special characters into identifiers.
 */
/* Comments
 * Ignored by the scanner and parser.
 */
/*
real			[\-]?{digit}+\.{digit}+([Ee][-+]?{digit}+)?
*/
/* some stuff needed for ecpg */
/* DO NOT PUT ANY COMMENTS IN THE FOLLOWING SECTION.
 * AT&T lex does not properly handle C-style comments in this second lex block.
 * So, put comments here. tgl - 1997-09-08
 *
 * Quoted strings must allow some special characters such as single-quote
 *  and newline.
 * Embedded single-quotes are implemented both in the SQL/92-standard
 *  style of two adjacent single quotes "''" and in the Postgres/Java style
 *  of escaped-quote "\'".
 * Other embedded escaped characters are matched explicitly and the leading
 *  backslash is dropped from the string. - thomas 1997-09-24
 */
#line 854 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 178 "pgc.l"

#line 1007 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 239 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1024 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 179 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 181 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 183 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 184 "pgc.l"
{
				before_comment = YYSTATE;
	 			BEGIN(xc);
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 189 "pgc.l"
{ BEGIN(before_comment); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 191 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 193 "pgc.l"
{
					BEGIN(xb);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 198 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,2);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad binary integer input!");
					return ICONST;
				}
	YY_BREAK
case 9:
#line 209 "pgc.l"
case 10:
YY_RULE_SETUP
#line 209 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 11:
#line 216 "pgc.l"
case 12:
YY_RULE_SETUP
#line 216 "pgc.l"
{
				}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 219 "pgc.l"
{
					BEGIN(xh);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 224 "pgc.l"
{
					char* endptr;

					BEGIN(SQL);
					errno = 0;
					yylval.ival = strtol((char *)literal,&endptr,16);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad hexadecimal integer input");
					return ICONST;
				}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 235 "pgc.l"
{
					BEGIN(xq);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 240 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(scanstr(literal));
					return SCONST;
				}
	YY_BREAK
case 17:
#line 246 "pgc.l"
case 18:
#line 247 "pgc.l"
case 19:
YY_RULE_SETUP
#line 247 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 253 "pgc.l"
{
				}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 257 "pgc.l"
{
					BEGIN(xd);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 262 "pgc.l"
{
					BEGIN(SQL);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 267 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 273 "pgc.l"
{
					BEGIN(xdc);
					llen = 0;
					*literal = '\0';
				}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 278 "pgc.l"
{
					BEGIN(C);
					yylval.str = mm_strdup(literal);
					return CSTRING;
				}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 283 "pgc.l"
{
					if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
						yyerror("ERROR: quoted string parse buffer exceeded");
					memcpy(literal+llen, yytext, yyleng+1);
					llen += yyleng;
				}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 290 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 291 "pgc.l"
{
					BEGIN(SQL);
					return yytext[0];
				}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 297 "pgc.l"
{ 	return TYPECAST; }
	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 298 "pgc.l"
{
					BEGIN(xm);
					return yytext[0];
				}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 302 "pgc.l"
{ /* 
				   * We may find a ';' inside a structure
				   * definition in a TYPE or VAR statement.
				   * This is not an EOL marker.
				   */
				  if (yytext[0] == ';' && struct_level == 0)
					 BEGIN C;
				  return yytext[0];
				}
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 311 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 315 "pgc.l"
{
					if (strcmp((char*)yytext,"!=") == 0)
						yylval.str = mm_strdup("<>"); /* compatability */
					else
						yylval.str = mm_strdup((char*)yytext);
					return Op;
				}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 322 "pgc.l"
{
					yylval.ival = atoi((char*)&yytext[1]);
					return PARAM;
				}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 326 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					BEGIN(xm);
					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 379 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 396 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.dval = strtod(((char *)yytext),&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float8 input");
					return FCONST;
				}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 406 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 422 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.dval = strtod((char *)yytext,&endptr);
					if (*endptr != '\0' || errno == ERANGE)
						yyerror("ERROR: Bad float input");
					return FCONST;
				}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 431 "pgc.l"
{
					char* endptr;

					BEGIN(xm);
					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 448 "pgc.l"
{
					char* endptr;

					errno = 0;
					yylval.ival = strtol((char *)yytext,&endptr,10);
					if (*endptr != '\0' || errno == ERANGE)
					{
						errno = 0;
						yylval.dval = strtod(((char *)yytext),&endptr);
						if (*endptr != '\0' || errno == ERANGE)
							yyerror("ERROR: Bad integer input");
						yyerror("WARNING: Integer input is out of range; promoted to float");
						return FCONST;
					}
					return ICONST;
				}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 464 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext+1);
					return(CVARIABLE);
			}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 468 "pgc.l"
{
					int i;
					ScanKeyword		*keyword;
					char lower_text[NAMEDATALEN];

					/* this should leave the last byte set to '\0' */
					strncpy(lower_text, yytext, NAMEDATALEN-1);
					for(i = 0; lower_text[i]; i++)
						if (isascii((unsigned char)lower_text[i]) && isupper(lower_text[i]))
							lower_text[i] = tolower(lower_text[i]);

					keyword = ScanKeywordLookup((char*)lower_text);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						keyword = ScanECPGKeywordLookup((char*)lower_text);
						if (keyword != NULL) {
							return keyword->value;
						}
						else
						{
							struct _defines *ptr;

							for (ptr = defines; ptr; ptr = ptr->next)
							{
								if (strcmp(yytext, ptr->old) == 0)
								{
									struct _yy_buffer *yb;

									yb = mm_alloc(sizeof(struct _yy_buffer));

						                        yb->buffer =  YY_CURRENT_BUFFER;
						                        yb->lineno = yylineno;
						                        yb->filename = mm_strdup(input_filename);
						                        yb->next = yy_buffer;

						                        yy_buffer = yb;

 									yy_scan_string(ptr->new);
									break;
								}
							}
							if (ptr == NULL) 
							{
								yylval.str = mm_strdup((char*)yytext);
								return IDENT;
							}
						}
					}
				}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 520 "pgc.l"
{ /* ignore */ }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 521 "pgc.l"
{ return yytext[0]; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 522 "pgc.l"
{ BEGIN SQL; return SQL_START; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 523 "pgc.l"
{ /* ignore */ } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 524 "pgc.l"
{
					yylval.str = mm_strdup((char*)yytext);
					return(CPP_LINE);
				}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 528 "pgc.l"
{
					ScanKeyword		*keyword;

					keyword = ScanCKeywordLookup((char*)yytext);
					if (keyword != NULL) {
						return keyword->value;
					}
					else
					{
						struct _defines *ptr;

						for (ptr = defines; ptr; ptr = ptr->next)
						{
							if (strcmp(yytext, ptr->old) == 0)
							{
								struct _yy_buffer *yb;

								yb = mm_alloc(sizeof(struct _yy_buffer));

					                        yb->buffer =  YY_CURRENT_BUFFER;
					                        yb->lineno = yylineno;
					                        yb->filename = mm_strdup(input_filename);
					                        yb->next = yy_buffer;

					                        yy_buffer = yb;

								yy_scan_string(ptr->new);
								break;
							}
						}
						if (ptr == NULL) 
						{
							yylval.str = mm_strdup((char*)yytext);
							return IDENT;
						}
					}
				}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 565 "pgc.l"
{ return(';'); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 566 "pgc.l"
{ return(','); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 567 "pgc.l"
{ return('*'); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 568 "pgc.l"
{ ECHO; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 569 "pgc.l"
{ return('{'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 570 "pgc.l"
{ return('}'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 571 "pgc.l"
{ return('['); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 572 "pgc.l"
{ return(']'); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 573 "pgc.l"
{ return('='); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 574 "pgc.l"
{ return S_ANYTHING; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 575 "pgc.l"
{BEGIN(def_ident);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 576 "pgc.l"
{}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 577 "pgc.l"
{
				old = mm_strdup(yytext);
				BEGIN(def);
				llen = 0;
				*literal = '\0';
			}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 583 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 584 "pgc.l"
{
				struct _defines *ptr, *this;
        
                                for (ptr = defines; ptr != NULL; ptr = ptr->next)
                                {
                                     if (strcmp(old, ptr->old) == 0)
                                     {
					free(ptr->new);
					ptr->new = mm_strdup(scanstr(literal));
                                     }
                                }
				if (ptr == NULL)
				{                        
                                        this = (struct _defines *) mm_alloc(sizeof(struct _defines));

                                        /* initial definition */
                                        this->old = old;
                                        this->new = mm_strdup(scanstr(literal));
					this->next = defines;
					defines = this;
				}

				BEGIN(C);
			}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 608 "pgc.l"
{
				if ((llen+yyleng) > (MAX_PARSE_BUFFER - 1))
					yyerror("ERROR: define statement parse buffer exceeded");
				memcpy(literal+llen, yytext, yyleng+1);
				llen += yyleng;
			}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 614 "pgc.l"
{ BEGIN(incl); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 615 "pgc.l"
/* eat the whitespace */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 616 "pgc.l"
{ /* got the include file name */
			  struct _yy_buffer *yb;
			  struct _include_path *ip;
			  char inc_file[PATH_MAX];

			  yb = mm_alloc(sizeof(struct _yy_buffer));

			  yb->buffer =  YY_CURRENT_BUFFER;
			  yb->lineno = yylineno;
			  yb->filename = input_filename;
			  yb->next = yy_buffer;

			  yy_buffer = yb;

			  if (yytext[strlen(yytext) - 1] == ';')
				yytext[strlen(yytext) - 1] = '\0';

			  yyin = NULL;
			  for (ip = include_paths; yyin == NULL && ip != NULL; ip = ip->next)
			  {
				if (strlen(ip->path) + strlen(yytext) + 3 > PATH_MAX)
				{
					fprintf(stderr, "Error: Path %s/%s is too long in line %d, skipping.\n", ip->path, yytext, yylineno);
					continue;
				}
			  	sprintf (inc_file, "%s/%s", ip->path, yytext);
		          	yyin = fopen( inc_file, "r" );
			  	if (!yyin)
				{
					if (strcmp(inc_file + strlen(inc_file) - 2, ".h"))
					{
						strcat(inc_file, ".h");
						yyin = fopen( inc_file, "r" );
					}

				}
			  }
			  if (!yyin)
			  {
				fprintf(stderr, "Error: Cannot open include file %s in line %d\n", yytext, yylineno);
				exit(NO_INCLUDE_FILE); 
			  }

			  input_filename = mm_strdup(inc_file);
			  yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE ));
			  yylineno = 0;
			  output_line_number();

			  BEGIN C;
			}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 666 "pgc.l"
{ BEGIN C; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(C):
case YY_STATE_EOF(SQL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(def):
case YY_STATE_EOF(def_ident):
case YY_STATE_EOF(xb):
case YY_STATE_EOF(xc):
case YY_STATE_EOF(xd):
case YY_STATE_EOF(xdc):
case YY_STATE_EOF(xh):
case YY_STATE_EOF(xm):
case YY_STATE_EOF(xq):
#line 667 "pgc.l"
{ if (yy_buffer == NULL)
				yyterminate();
			  else
			  {
				struct _yy_buffer *yb = yy_buffer;

				if (yyin != NULL)
					fclose(yyin);

				yy_delete_buffer( YY_CURRENT_BUFFER );
				yy_switch_to_buffer(yy_buffer->buffer);

				yylineno = yy_buffer->lineno;

				free(input_filename);
				input_filename = yy_buffer->filename;

				yy_buffer = yy_buffer->next;
				free(yb);
				output_line_number();
			  }
			}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 689 "pgc.l"
ECHO;
	YY_BREAK
#line 1909 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 239 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 239 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 238);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 689 "pgc.l"

void
lex_init(void)
{
    braces_open = 0;
    BEGIN C;
}

int yywrap(void) 
{ 
    return 1;
}
