#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for regress/sql (the regression test)
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

CLFILES=	create_function_1.sql create_function_2.sql copy.sql misc.sql constraints.sql

clean:
	rm -f $(CLFILES)
