#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/index
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

SUBSRCS+= genam.c indexam.c istrat.c
