#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for the postmaster module
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

VPATH:= $(VPATH):$(CURDIR)/postmaster

SRCS_POSTMASTER= postmaster.c
