# $PostgreSQL$

subdir = contrib/miscutil
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = misc_utils
DATA_built = misc_utils.sql
DOCS = README.misc_utils

include $(top_srcdir)/contrib/contrib-global.mk
