# $Header$

subdir = contrib/btree_gist
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

MODULES = btree_gist
DATA_built = btree_gist.sql
DOCS = README.btree_gist
REGRESS = btree_gist

include $(top_srcdir)/contrib/contrib-global.mk
