#-------------------------------------------------------------------------
#
# $PostgreSQL$
#
#-------------------------------------------------------------------------
subdir = src/backend/utils/mb/conversion_procs/utf8_and_win1252
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

NAME		:= utf8_and_win1252

include $(srcdir)/../proc.mk
