#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for the Tioga module
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header$
#
#-------------------------------------------------------------------------

VPATH:= $(VPATH):$(CURDIR)/tioga

SRCS_TIOGA= tgRecipe.c Varray.c

HEADERS+= tgRecipe.h Arr_TgRecipe.h Varray.h



