#!/bin/sh

# $PostgreSQL$

rm -f ./TAGS
find `pwd`/ -type f -name '*.[chyl]' -print | \
  xargs etags --append -o TAGS

find . -type d -print | \
while read DIR; do
  [ "$DIR" != "." ] && ln -f -s `pwd`/TAGS $DIR
done
